'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {AmpRig,modelMap,visibleControls,validate}=require('../ui/amp_state.js');
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../catalog.json'),'utf8')),models=modelMap(catalog);
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
const make=()=>new AmpRig(catalog);
test('valid empty-integration state has independent six lane banks',()=>{const r=make();assert.equal(Object.keys(r.state.lanes).length,6);assert(validate(r.state,models));});
test('selecting another amp remembers its own values',()=>{const r=make();r.set('hw.normal.volume',.23);r.choose('legacy.amp.1');r.set('hw.normal',.72);r.choose('legacy.amp.0');assert.equal(r.current().parameters['hw.normal.volume'],.23);});
test('ZUTA channel values are independent',()=>{const r=make();r.choose('planned.amp.zuta-gbg120');r.set('ch1.gain',.19);r.channel('ch4');r.set('ch4.gain',.87);r.channel('ch1');assert.equal(r.current().parameters['ch1.gain'],.19);assert.equal(r.current().parameters['ch4.gain'],.87);});
test('shared EQ is one actual key across 6505 channels',()=>{const r=make();r.choose('legacy.amp.2');r.set('hw.mid',.14);r.channel('rhythm');assert.equal(r.current().parameters['hw.mid'],.14);assert(!Object.hasOwn(r.current().parameters,'hw.rhythm.mid'));});
test('two identical amps on Dual lanes remain independent',()=>{const r=make();r.setMode('Dual');r.set('hw.normal.volume',.2);r.setLane('b');r.set('hw.normal.volume',.8);r.setLane('a');assert.equal(r.current().parameters['hw.normal.volume'],.2);});
test('mode changes preserve hidden lane banks',()=>{const r=make();r.setMode('Matrix');r.setLane('high');r.choose('planned.amp.svt-cl');r.set('hw.master',.7);r.setMode('Classic');r.setMode('Matrix');assert.equal(r.current().laneId,'high');assert.equal(r.current().parameters['hw.master'],.7);});
test('Chimera output level never changes native master',()=>{const r=make();r.choose('planned.amp.svt-cl');const old=r.current().parameters;r.trim('laneLevel',-8);assert.deepEqual(r.current().parameters,old);});
test('native master never changes lane trim',()=>{const r=make();r.choose('planned.amp.svt-cl');r.trim('laneLevel',-8);r.set('hw.master',.9);assert.equal(r.current().utility.laneLevel,-8);});
test('input jack selection stores independently',()=>{const r=make();r.route(1);assert.equal(r.current().route,1);assert.equal(r.current().parameters['hw.normal.bright'],0);});
test('all 24 serialized panel defaults validate',()=>{const r=make();assert.equal(models.size,24);for(const id of models.keys()){r.choose(id);assert(validate(r.state,models));}});
test('roundtrip contains channel values and independent utilities',()=>{const r=make();r.choose('legacy.amp.4');r.set('hw.lead.drive',.71);r.trim('inputTrim',4);const other=make();other.load(r.export());assert.deepEqual(other.state,r.state);});
test('malformed JSON rejected atomically',()=>{const r=make(),before=r.state;assert.throws(()=>r.load('{'));assert.deepEqual(r.state,before);});
test('old pedal format cannot be mistaken for amps',()=>{const r=make();assert.throws(()=>r.load(JSON.stringify({version:1,effects:[]})));});
test('unknown model rejects without modifying state',()=>{const r=make(),s=r.state;assert.throws(()=>r.choose('planned.sd1'));assert.deepEqual(r.state,s);});
test('unknown control rejects atomically',()=>{const r=make(),s=r.state;assert.throws(()=>r.set('hw.fake',.2));assert.deepEqual(r.state,s);});
test('NaN and infinity rejected',()=>{const r=make();for(const v of [NaN,Infinity,-Infinity])assert.throws(()=>r.set('hw.normal.volume',v));});
test('out-of-range values rejected not silently clamped',()=>{const r=make();for(const v of [-.1,1.1,'0.5',true,null])assert.throws(()=>r.set('hw.normal.volume',v));});
test('choice requires integer in range',()=>{const r=make();r.choose('planned.amp.svt-cl');for(const v of [1.5,-1,5])assert.throws(()=>r.set('hw.mid_frequency',v));});
test('unknown or wrong-mode lane rejected',()=>{const r=make();assert.throws(()=>r.setLane('b'));assert.throws(()=>r.setMode('Other'));});
test('invalid route and utility rejected',()=>{const r=make();assert.throws(()=>r.route(30));assert.throws(()=>r.trim('laneLevel',25));assert.throws(()=>r.trim('master',0));});
test('exported snapshots cannot mutate internal state',()=>{const r=make(),s=r.state;s.mode='Matrix';assert.equal(r.state.mode,'Classic');const c=r.current();c.parameters['hw.normal.volume']=.1;assert.equal(r.current().parameters['hw.normal.volume'],.5);});
test('undo redo restores exact per-amp memory',()=>{const r=make();const before=r.state;r.choose('legacy.amp.4');r.undo();assert.deepEqual(r.state,before);r.redo();assert.equal(r.current().model,'legacy.amp.4');});
test('bad import missing or extra parameter rejected',()=>{const r=make(),s=r.state;delete s.lanes.main.bank['legacy.amp.0'].parameters['hw.normal.volume'];assert.throws(()=>r.load(JSON.stringify(s)));const t=r.state;t.lanes.main.bank['legacy.amp.0'].parameters['bad']=0;assert.throws(()=>r.load(JSON.stringify(t)));});
test('future schema rejected',()=>{const r=make(),s=r.state;s.version=99;assert.throws(()=>r.load(JSON.stringify(s)));});
test('unselected bank errors are also rejected',()=>{const r=make();r.choose('legacy.amp.1');const s=r.state;s.lanes.main.bank['legacy.amp.0'].parameters['hw.normal.volume']=9;assert.throws(()=>r.load(JSON.stringify(s)));});
test('full bank roundtrip within 1MB',()=>{const r=make();for(const id of models.keys())r.choose(id);assert(r.export().length<1048576);const r2=make();r2.load(r.export());assert.deepEqual(r2.state,r.state);});
test('visible controls include shared but not other channels',()=>{const m=models.get('legacy.amp.2'),keys=visibleControls(m,'rhythm').map(c=>c.id);assert(keys.includes('hw.mid'));assert(!keys.includes('hw.lead.pre_gain'));});
test('SVT-VR second channel never exposes middle',()=>{const m=models.get('legacy.amp.5'),keys=visibleControls(m,'ch2').map(c=>c.id);assert(!keys.some(k=>k.includes('mid')));});
test('1000 deterministic edits keep normalized contract',()=>{const r=make();for(let i=0;i<1000;i++){r.set('hw.normal.volume',(i%101)/100);if(i%13===0){r.undo();r.redo();}}assert(validate(r.state,models));});
test('prototype-polluting import keys rejected',()=>{const r=make(),s=r.state;const text=JSON.stringify(s).replace('"lanes":{','"lanes":{"__proto__":{},');assert.throws(()=>r.load(text));});
console.log(`${count} amplifier state cases passed`);
