'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {Board,encode,decode}=require('../ui/state.js');
const {defaults,prepareState,displayLabel}=require('../ui/control_state.js');
const catalog=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../catalog.json'),'utf8'));
const models=new Map(catalog.models.map(m=>[m.id,m]));
const old=catalog.models.filter(m=>m.legacy_controls);
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
const legacyState=m=>({version:1,nextId:2,lowTap:1,engine:'legacy-v1',effects:[{id:1,model:m.id,bypass:true,parameters:Object.fromEntries(m.legacy_controls.map(c=>[c.id,c.initial])),midi:{74:m.legacy_controls[0].id}}]});
test('25 models use distinct hardware and raw keys',()=>{assert.equal(old.length,25);for(const m of old){const x=defaults(m);assert.equal(Object.keys(x).length,m.controls.length+m.legacy_controls.length);}});
test('25 old states preserve exact raw values and old MIDI',()=>{for(const m of old){const s=legacyState(m),snapshot=JSON.stringify(s),r=prepareState(s,models);assert.equal(r.migrated,1);assert.equal(JSON.stringify(s),snapshot);for(const [k,v]of Object.entries(s.effects[0].parameters))assert.equal(r.state.effects[0].parameters[k],v);assert.deepEqual(r.state.effects[0].midi,s.effects[0].midi);assert.equal(r.state.lowTap,1);}});
test('old input/amount is not converted to original input position',()=>{const s=legacyState(models.get('legacy.comp.0'));s.effects[0].parameters.precomp=.93;const r=prepareState(s,models);assert.equal(r.state.effects[0].parameters['hw.input'],.5);assert.equal(r.state.effects[0].parameters.precomp,.93);});
test('native edit leaves legacy values unchanged',()=>{const m=models.get('legacy.comp.1'),b=new Board(),id=b.add(m.id,defaults(m));b.set(id,'hw.sensitivity',.77);assert.equal(b.state.effects[0].parameters.precomp,.35);const r=prepareState(decode(encode(b.state)),models);assert.equal(r.migrated,0);assert.deepEqual(r.state,b.state);});
test('unknown keys fail instead of silently reassigning',()=>{const m=old[0],s=legacyState(m);s.effects[0].parameters.fake=.3;assert.throws(()=>prepareState(s,models));});
test('partial legacy and partial hardware maps both fail',()=>{const m=old[0],s=legacyState(m);delete s.effects[0].parameters.pretone;assert.throws(()=>prepareState(s,models));s.effects[0].parameters=defaults(m);delete s.effects[0].parameters['hw.tone'];assert.throws(()=>prepareState(s,models));});
test('invalid hardware ranges and fractional choices fail',()=>{const m=models.get('legacy.comp.0'),s=legacyState(m);s.effects[0].parameters=defaults(m);s.effects[0].parameters['hw.ratio']=.5;assert.throws(()=>prepareState(s,models));s.effects[0].parameters['hw.ratio']=0;s.effects[0].parameters['hw.input']=2;assert.throws(()=>prepareState(s,models));});
test('AW3 physical controls change labels without changing IDs',()=>{const m=models.get('legacy.filter.4'),p=defaults(m);p['hw.mode']=3;assert.equal(displayLabel(m.controls[1],p),'VOWEL 2');assert.equal(displayLabel(m.controls[2],p),'VOWEL 1');assert.equal(m.controls.length,4);p['hw.mode']=0;assert.equal(displayLabel(m.controls[1],p),'MANUAL');});
test('new native duplicate remains within five and independently writable',()=>{const m=old[0],b=new Board();for(let i=0;i<5;i++)b.add(m.id,defaults(m));assert.throws(()=>b.duplicate(b.state.effects[0].id));b.set(b.state.effects[0].id,'hw.tone',.9);assert.equal(b.state.effects[1].parameters['hw.tone'],.5);});
test('planned controls retain preexisting schema and CBP compatibility',()=>{const m=models.get('planned.jb2'),b=new Board();b.add(m.id,defaults(m));assert.equal(Object.keys(b.state.effects[0].parameters).length,7);assert.deepEqual(prepareState(decode(encode(b.state)),models).state,b.state);});
console.log(`${count} control-state cases passed`);
