#!/usr/bin/env python3
"""Generate production POST controls from reviewed rack panel identities.

Units/ranges here are explicit software implementation choices. They do not
certify measured hardware tapers. Physical-only controls remain visible disabled.
"""
import json,pathlib,sys
root=pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'Preparation'))
from rack_controls import rack_panels
panels=rack_panels()
names=['Console VCA','FET Limiter','Optical Level','Iron Colour','Pure DI','Blue Channel','Console Four','Inductor EQ','Passive Tube']
# physical ranges / meaningful initial values for THIS digital implementation.
ranges={
'legacy.bus.0':{'threshold':(-48,0,-18),'makeup':(0,20,0),'fade_rate':(1,60,10)},
'legacy.bus.1':{'input':(-24,36,0),'output':(-36,12,0),'attack':(0,1,.5),'release':(0,1,.5)},
'legacy.bus.2':{'gain':(-24,24,0),'peak_reduction':(0,100,40),'r37':(0,1,1)},
'legacy.preamp.2':{'trim':(0,20,0),'instrument_gain':(10,40,10)},
'legacy.eq.0':{'hf_gain':(-18,18,0),'hf_frequency':(1500,22000,8000),'hmf_gain':(-18,18,0),'hmf_frequency':(600,7000,2000),'hmf_q':(.3,6,1),'lmf_gain':(-18,18,0),'lmf_frequency':(200,2500,600),'lmf_q':(.3,6,1),'lf_gain':(-18,18,0),'lf_frequency':(30,450,80)},
'legacy.eq.1':{'hf_gain':(-16,16,0),'mf_gain':(-18,18,0),'lf_gain':(-16,16,0)},
'legacy.eq.2':{'lf_boost':(0,13.5,0),'lf_atten':(0,17.5,0),'bandwidth':(0,1,.5),'hf_boost':(0,18,0),'hf_atten':(0,16,0)}}
initials={('legacy.bus.0','attack'):4,('legacy.bus.0','release'):1,('legacy.bus.0','ratio'):1,('legacy.preamp.0','gain'):2,('legacy.preamp.1','tone'):0,('legacy.preamp.2','input'):1,('legacy.preamp.2','impedance'):1}
physical={'legacy.bus.0':{'external_sidechain':'External sidechain bus is unavailable; internal stereo detector is used.'},'legacy.preamp.2':{'impedance':'Physical microphone loading requires a source impedance model; unavailable for recorded audio.','phantom':'Physical phantom power; unavailable in a software insert.','insert':'External send/return is unavailable; internal signal path remains direct.','instrument_z':'Physical instrument loading requires a pickup/source circuit; unavailable for recorded audio.'}}
def s(v):return json.dumps(v,ensure_ascii=False)
lines=['// Generated by Tools/generate_post_native_catalog.py. Do not hand-edit.','#pragma once','#include <juce_core/juce_core.h>','#include <array>','#include <cmath>','namespace spectralforge {','inline constexpr int postNativeSectionCount=3, postNativeModelsPerSection=3, postNativeMaxControls=14;','enum class PostNativeControlKind { knob, choice, toggle };','struct PostNativeControl { const char* id; const char* label; PostNativeControlKind kind; float minimum, maximum, initial, interval; const char* options; bool connected; const char* note; };','struct PostNativeModel { const char* name; const char* reference; int controlCount; std::array<PostNativeControl,postNativeMaxControls> controls; };','inline const std::array<PostNativeModel,9> postNativeModels{{']
for idx,(mid,p) in enumerate(panels.items()):
    lines += ['    {'+s(names[idx])+','+s(p['reference'])+','+str(len(p['controls']))+', {{']
    for c in p['controls']:
        key=c['id'][3:]; kind=c['kind']; choices=c.get('options',[])
        lo,hi,initial=(0,len(choices)-1,c['initial']) if choices else ((0,1,c['initial']) if kind=='toggle' else ranges.get(mid,{}).get(key,(0,1,c['initial'])))
        initial=initials.get((mid,key),initial)
        disabled=physical.get(mid,{}).get(key)
        note=disabled or (c.get('note','')+' '+('Digital implementation range; hardware taper uncalibrated.' if kind=='knob' else '')).strip()
        if mid=='legacy.preamp.1' and key=='input':note='Recorded-audio input voicing; MIC +48 V shares MIC response without phantom power.'
        if mid=='legacy.preamp.2' and key=='post_insert':note='Meter source switches between input and processed output; no external insert.'
        if mid=='legacy.bus.1' and key=='meter':note='GR/output meter selection; OFF bypasses processing and blanks meter (software power proxy).'
        lines += ['        {'+','.join([s(key),s(c['label']),'PostNativeControlKind::'+kind,*[f'{float(v)}f' for v in (lo,hi,initial,1 if kind!='knob' else .001 if hi<=6 else .01)],s('|'.join(choices)),str(not bool(disabled)).lower(),s(note)])+'},']
    lines += ['    }}},']
lines += ['}};','inline const PostNativeModel& postNativeModel(int section,int model) { return postNativeModels[static_cast<size_t>(juce::jlimit(0,2,section)*3+juce::jlimit(0,2,model))]; }','inline juce::String postNativePrefix(int section) { static const char* names[]{"bus","preamp","eq"}; return "pn_"+juce::String(names[juce::jlimit(0,2,section)]); }','inline juce::String postNativeModeID(int s) { return postNativePrefix(s)+"_native"; }','inline juce::String postNativeModelID(int s) { return postNativePrefix(s)+"_model"; }','inline juce::String postNativeBankPrefix(int s,int m) { return postNativePrefix(s)+"_m"+juce::String(m); }','inline juce::String postNativeBypassID(int s,int m) { return postNativeBankPrefix(s,m)+"_bypass"; }','inline juce::String postNativeTrimID(int s,int m) { return postNativeBankPrefix(s,m)+"_softwareTrim"; }','inline juce::String postNativeLevelID(int s,int m) { return postNativeBankPrefix(s,m)+"_softwareLevel"; }','inline juce::String postNativeControlID(int s,int m,int c) { return postNativeBankPrefix(s,m)+"_"+postNativeModel(s,m).controls[static_cast<size_t>(c)].id; }','struct PostNativeBank { bool bypass{true}; float trimDb{},levelDb{}; std::array<float,postNativeMaxControls> values{}; };','struct PostNativeSectionState { bool nativeEnabled{false}; int selected{}; std::array<PostNativeBank,3> banks{}; };','struct PostNativeState { std::array<PostNativeSectionState,3> sections{}; };','inline PostNativeState defaultPostNativeState(bool nativeEnabled=true) { PostNativeState state; for(int s=0;s<3;++s) { state.sections[s].nativeEnabled=nativeEnabled; for(int m=0;m<3;++m)for(int c=0;c<postNativeModel(s,m).controlCount;++c)state.sections[s].banks[m].values[c]=postNativeModel(s,m).controls[c].initial; } return state; }','inline void sanitisePostNativeState(PostNativeState& state) { for(int s=0;s<3;++s) { auto& section=state.sections[s]; section.selected=juce::jlimit(0,2,section.selected); for(int m=0;m<3;++m) { auto& bank=section.banks[m]; bank.trimDb=std::isfinite(bank.trimDb)?juce::jlimit(-24.f,24.f,bank.trimDb):0.f; bank.levelDb=std::isfinite(bank.levelDb)?juce::jlimit(-24.f,24.f,bank.levelDb):0.f; for(int c=0;c<postNativeModel(s,m).controlCount;++c) { const auto& spec=postNativeModel(s,m).controls[c]; float& value=bank.values[c]; value=std::isfinite(value)?juce::jlimit(spec.minimum,spec.maximum,value):spec.initial; if(spec.kind!=PostNativeControlKind::knob)value=std::round(value); if(!spec.connected)value=spec.initial; } } } }','} // namespace spectralforge']
(root/'Source/PostNativeCatalog.h').write_text('\n'.join(lines)+'\n')
