#!/usr/bin/env python3
"""Compile reviewed panel targets into production-native control definitions.

Panel definitions and uncertainty remain sourced from Preparation. This file
never promotes those targets to measured hardware/circuit equivalence.
"""
import json
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'Preparation'))
from amp_controls import amp_panels

def q(s): return json.dumps(s,ensure_ascii=True)
def generate():
    panels=amp_panels()
    keys=[f'legacy.amp.{i}' for i in range(15)]+['planned.amp.'+k for k in ('zuta-gbg120','engl','diezel-vh4','svt-cl','sunn','fortin','soldano','bogner','engl-e670fe')]
    out=['#pragma once','// Generated by Tools/generate_amp_native_catalog.py; source: Preparation/amp_controls.py.', '#include "AmpCatalog.h"','#include "OriginalAmpDefinition.h"','#include <array>','#include <span>','#include <string_view>','#include <cmath>', 'namespace spectralforge {',
    'inline constexpr int ampNativeContextCount=6, maxAmpNativeControls=42;',
    'enum class AmpNativeControlKind { knob, choice, toggle };',
    'struct AmpNativeControl { const char* key; const char* label; const char* group; AmpNativeControlKind kind; unsigned channelMask; std::span<const char* const> options; float initial; float minimum,maximum; };',
    'struct AmpNativePanel { const char* reference; const char* reviewStatus; std::span<const AmpNativeControl> controls; std::span<const char* const> channels; std::span<const char* const> channelKeys; std::span<const char* const> routes; int defaultChannel; };']
    for m,key in enumerate(keys):
        p=panels[key];channels=[c['id'] for c in p['channels']]
        for c,x in enumerate(p['controls']):
            opts=x.get('options', ['OFF','ON'] if x['kind']=='toggle' else [])
            if opts:out.append(f'inline constexpr const char* nativeOptions_{m}_{c}[]={{'+','.join(q(x) for x in opts)+'};')
        out.append(f'inline constexpr AmpNativeControl nativeControls_{m}[]={{')
        for c,x in enumerate(p['controls']):
            mask=sum(1<<channels.index(ch) for ch in x['channels']) if x['channels'] else (1<<len(channels))-1
            options=f'nativeOptions_{m}_{c}' if x['kind']!='knob' else '{}'
            maximum=len(x.get('options',[]))-1 if x['kind']=='choice' else 1
            out.append(' {'+','.join([q(x['id']),q(x['label']),q(x['group']),f'AmpNativeControlKind::{x["kind"]}',str(mask),options,str(float(x['initial']))+'f','0.f',str(float(maximum))+'f'])+'},')
        out.append('};')
        for what,arr in [('Channels',[c['label'] for c in p['channels']]),('ChannelKeys',channels),('Routes',[r.replace(' — routing target','').replace(' — target','') for r in p['input_routes']])]:
            # Channel menu never repeats actual original amplifier model names.
            if m==20 and what=='Channels':arr=['GAIN I','GAIN II','CLEAN']
            out.append(f'inline constexpr const char* native{what}_{m}[]={{'+','.join(q(x) for x in arr)+'};')
    out += ['inline constexpr auto nativeOriginalControls=[] {',
            '    std::array<AmpNativeControl,original::controlCount> result{};',
            '    for(size_t i=0;i<result.size();++i){const auto& c=original::controls[i];result[i]={c.id,c.label,i<8?"AMPLIFIER":"CHARACTER",AmpNativeControlKind::knob,31,{},original::channelState(0).values[i],c.minimum,c.maximum};}',
            '    return result;', '}();',
            'inline constexpr auto& nativeOriginalChannels=original::channelNames;',
            'inline constexpr auto& nativeOriginalKeys=original::channelKeys;',
            'inline constexpr const char* nativeOriginalRoutes[]={"INPUT"};']
    out.append('inline constexpr std::array<AmpNativePanel,ampModelCount> ampNativePanels{{')
    for m,key in enumerate(keys):
        p=panels[key];ch=[c['id'] for c in p['channels']]
        out.append(' {'+','.join([q(p['reference']),q(p['review_status']),f'nativeControls_{m}',f'nativeChannels_{m}',f'nativeChannelKeys_{m}',f'nativeRoutes_{m}',str(ch.index(p['initial_channel']))])+'},')
    out.append(' {"SpectralForge Original","authored_reference_informed",nativeOriginalControls,nativeOriginalChannels,nativeOriginalKeys,nativeOriginalRoutes,0},')
    out+=['}};',
    'inline const AmpNativePanel& ampNativePanel(int model) noexcept { return ampNativePanels[(size_t)juce::jlimit(0,ampModelCount-1,model)]; }',
    'inline int ampNativeContext(int mode,int lane) noexcept { return mode==0?0:mode==1?1+juce::jlimit(0,1,lane):3+juce::jlimit(0,2,lane); }',
    'inline bool ampNativeControlVisible(int model,int control,int channel) noexcept { const auto& p=ampNativePanel(model); return control>=0 && control<(int)p.controls.size() && channel>=0 && channel<(int)p.channels.size() && (p.controls[(size_t)control].channelMask & (1u<<channel))!=0; }',
    'struct AmpNativeState { bool enabled{},soloEnabled{},originalModern{true}; int model{},channel{},inputRoute{}; float inputTrimDb{},outputLevelDb{}; std::array<float,maxAmpNativeControls> values{}; bool operator==(const AmpNativeState&) const = default; };',
    'inline AmpNativeState defaultAmpNativeState(int model) noexcept { AmpNativeState s; s.enabled=true;s.model=juce::jlimit(0,ampModelCount-1,model);const auto& p=ampNativePanel(s.model);s.channel=p.defaultChannel;for(size_t c=0;c<p.controls.size();++c)s.values[c]=p.controls[c].initial;return s; }',
    'inline void sanitiseAmpNativeState(AmpNativeState& s) noexcept { s.inputTrimDb=std::isfinite(s.inputTrimDb)?juce::jlimit(-24.f,24.f,s.inputTrimDb):0.f;s.outputLevelDb=std::isfinite(s.outputLevelDb)?juce::jlimit(-24.f,24.f,s.outputLevelDb):0.f;s.model=juce::jlimit(0,ampModelCount-1,s.model);const auto& p=ampNativePanel(s.model);s.channel=juce::jlimit(0,(int)p.channels.size()-1,s.channel);s.inputRoute=juce::jlimit(0,(int)p.routes.size()-1,s.inputRoute);for(size_t c=0;c<p.controls.size();++c){const auto& k=p.controls[c];auto& v=s.values[c];v=std::isfinite(v)?juce::jlimit(k.minimum,k.maximum,v):k.initial;if(k.kind!=AmpNativeControlKind::knob)v=std::round(v);}}',
    'inline int ampNativeControlIndex(int model,std::string_view key) noexcept { const auto& p=ampNativePanel(model);for(size_t i=0;i<p.controls.size();++i)if(key==p.controls[i].key)return(int)i;return -1; }',
    'inline float ampNativeValue(const AmpNativeState& s,std::string_view key,float fallback=.5f) noexcept { const int i=ampNativeControlIndex(s.model,key);return i>=0?s.values[(size_t)i]:fallback; }',
    '} // namespace spectralforge']
    (ROOT/'Source/AmpNativeCatalog.h').write_text('\n'.join(out)+'\n')
if __name__=='__main__':generate()
