#include "PreFxRack.h"
#include <cmath>
namespace spectralforge {
void PreFxRack::prepare(const juce::dsp::ProcessSpec&s){sampleRate=s.sampleRate;compressor.prepare(s);drivePre.prepare(s);driveTone.prepare(s);low.prepare(s);mid.prepare(s);high.prepare(s);driveDry.setSize((int)s.numChannels,(int)s.maximumBlockSize);reset();setDrive(DriveModel::greenDrive,.35f,.5f,0.f,1.f,false);setEq(0,0,0,false);}
void PreFxRack::reset(){compressor.reset();drivePre.reset();driveTone.reset();low.reset();mid.reset();high.reset();}
void PreFxRack::setGate(float db,bool e){gateThreshold=juce::Decibels::decibelsToGain(db);gateOn=e;}
void PreFxRack::setCompressor(float t,float r,float a,float rel,bool e){compOn=e;compressor.setThreshold(t);compressor.setRatio(r);compressor.setAttack(a);compressor.setRelease(rel);}
void PreFxRack::setBoost(float db,bool e){boostGain=juce::Decibels::decibelsToGain(db);boostOn=e;}
void PreFxRack::setDrive(DriveModel model,float d,float t,float levelDb,float mix,bool e){driveModel=model;drive=juce::jlimit(0.f,1.f,d);tone=juce::jlimit(0.f,1.f,t);driveLevel=juce::Decibels::decibelsToGain(levelDb);driveMix=juce::jlimit(0.f,1.f,mix);driveOn=e;
 if(model==DriveModel::greenDrive){drivePre.state=juce::dsp::IIR::Coefficients<float>::makeHighPass(sampleRate,720.f);driveTone.state=juce::dsp::IIR::Coefficients<float>::makeLowPass(sampleRate,juce::jmap(tone,1800.f,7200.f));}
 else{drivePre.state=juce::dsp::IIR::Coefficients<float>::makeHighPass(sampleRate,70.f);const float fc=juce::jmap(tone,650.f,4200.f);driveTone.state=juce::dsp::IIR::Coefficients<float>::makePeakFilter(sampleRate,fc,.65f,juce::Decibels::decibelsToGain(juce::jmap(tone,-8.f,6.f)));}}
void PreFxRack::setEq(float l,float m,float h,bool e){eqOn=e;low.state=juce::dsp::IIR::Coefficients<float>::makeLowShelf(sampleRate,120.f,.707f,juce::Decibels::decibelsToGain(l));mid.state=juce::dsp::IIR::Coefficients<float>::makePeakFilter(sampleRate,850.f,.8f,juce::Decibels::decibelsToGain(m));high.state=juce::dsp::IIR::Coefficients<float>::makeHighShelf(sampleRate,3500.f,.707f,juce::Decibels::decibelsToGain(h));}
void PreFxRack::process(juce::AudioBuffer<float>&b){if(gateOn)for(int ch=0;ch<b.getNumChannels();++ch){auto*p=b.getWritePointer(ch);for(int n=0;n<b.getNumSamples();++n)if(std::abs(p[n])<gateThreshold)p[n]=0.f;}if(compOn){juce::dsp::AudioBlock<float>bl(b);juce::dsp::ProcessContextReplacing<float>ctx(bl);compressor.process(ctx);}if(boostOn)b.applyGain(boostGain);
 if(driveOn){for(int ch=0;ch<b.getNumChannels();++ch)driveDry.copyFrom(ch,0,b,ch,0,b.getNumSamples());{juce::dsp::AudioBlock<float>bl(b);juce::dsp::ProcessContextReplacing<float>ctx(bl);drivePre.process(ctx);}const float g=driveModel==DriveModel::greenDrive?juce::jmap(drive,1.8f,18.f):juce::jmap(drive,4.f,35.f);for(int ch=0;ch<b.getNumChannels();++ch){auto*p=b.getWritePointer(ch);for(int n=0;n<b.getNumSamples();++n){float x=p[n]*g;if(driveModel==DriveModel::greenDrive)p[n]=std::tanh(x+.08f*x*x);else{float a=std::tanh(x);p[n]=std::tanh(a*(2.2f+drive*4.f));}}}{juce::dsp::AudioBlock<float>bl(b);juce::dsp::ProcessContextReplacing<float>ctx(bl);driveTone.process(ctx);}b.applyGain(driveLevel*driveMix);for(int ch=0;ch<b.getNumChannels();++ch)b.addFrom(ch,0,driveDry,ch,0,b.getNumSamples(),1.f-driveMix);}
 if(eqOn){juce::dsp::AudioBlock<float>bl(b);juce::dsp::ProcessContextReplacing<float>ctx(bl);low.process(ctx);mid.process(ctx);high.process(ctx);}}
}
