# Explicit image assets used by the CAB visual panel.
# These illustrations do not add microphone responses or alter existing audio.
list(APPEND CHIMERA_ARTWORK
  "${CMAKE_CURRENT_LIST_DIR}/cab-guitar-412.png"
  "${CMAKE_CURRENT_LIST_DIR}/cab-bass-410.png"
  "${CMAKE_CURRENT_LIST_DIR}/speaker-guitar-12.png"
  "${CMAKE_CURRENT_LIST_DIR}/speaker-bass-10.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-attack-dynamic.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-body-ribbon.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-detail-condenser.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-57.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-421.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-441.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-906.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-20.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-7.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-201.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-88.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-dynamic-112.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-ribbon-121.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-ribbon-160.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-ribbon-4038.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-condenser-87.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-condenser-414.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-condenser-184.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-condenser-47-fet.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-condenser-4050.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-condenser-201-fet.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-condenser-67.png"
  "${CMAKE_CURRENT_LIST_DIR}/mic-chimera-strike.png"
  "${CMAKE_CURRENT_LIST_DIR}/room-studio.png"
)
