#pragma once
// Generated by Tools/generate_amp_native_catalog.py; source: Preparation/amp_controls.py.
#include "AmpCatalog.h"
#include "OriginalAmpDefinition.h"
#include <array>
#include <span>
#include <string_view>
#include <cmath>
namespace spectralforge {
inline constexpr int ampNativeContextCount=6, maxAmpNativeControls=42;
enum class AmpNativeControlKind { knob, choice, toggle };
struct AmpNativeControl { const char* key; const char* label; const char* group; AmpNativeControlKind kind; unsigned channelMask; std::span<const char* const> options; float initial; float minimum,maximum; };
struct AmpNativePanel { const char* reference; const char* reviewStatus; std::span<const AmpNativeControl> controls; std::span<const char* const> channels; std::span<const char* const> channelKeys; std::span<const char* const> routes; int defaultChannel; };
inline constexpr const char* nativeOptions_0_4[]={"OFF","ON"};
inline constexpr const char* nativeOptions_0_9[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_0[]={
 {"hw.normal.volume","VOLUME","NORMAL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.normal.treble","TREBLE","NORMAL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.normal.middle","MIDDLE","NORMAL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.normal.bass","BASS","NORMAL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.normal.bright","BRIGHT","NORMAL",AmpNativeControlKind::toggle,1,nativeOptions_0_4,0.0f,0.f,1.0f},
 {"hw.vibrato.volume","VOLUME","VIBRATO",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.vibrato.treble","TREBLE","VIBRATO",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.vibrato.middle","MIDDLE","VIBRATO",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.vibrato.bass","BASS","VIBRATO",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.vibrato.bright","BRIGHT","VIBRATO",AmpNativeControlKind::toggle,2,nativeOptions_0_9,0.0f,0.f,1.0f},
 {"hw.vibrato.reverb","REVERB","VIBRATO / FX",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.vibrato.speed","SPEED","VIBRATO / FX",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.vibrato.intensity","INTENSITY","VIBRATO / FX",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_0[]={"NORMAL","VIBRATO"};
inline constexpr const char* nativeChannelKeys_0[]={"normal","vibrato"};
inline constexpr const char* nativeRoutes_0[]={"INPUT 1","INPUT 2"};
inline constexpr AmpNativeControl nativeControls_1[]={
 {"hw.high_treble","LOUDNESS I / HIGH TREBLE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.normal","LOUDNESS II / NORMAL","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.middle","MIDDLE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.bass","BASS","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.presence","PRESENCE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_1[]={"SINGLE"};
inline constexpr const char* nativeChannelKeys_1[]={"single"};
inline constexpr const char* nativeRoutes_1[]={"HIGH TREBLE HIGH","HIGH TREBLE LOW","NORMAL HIGH","NORMAL LOW","JUMPED"};
inline constexpr const char* nativeOptions_2_9[]={"OFF","ON"};
inline constexpr const char* nativeOptions_2_10[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_2[]={
 {"hw.low","LOW","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.mid","MID","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.high","HIGH","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.resonance","RESONANCE","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.presence","PRESENCE","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.rhythm.pre_gain","PRE GAIN","RHYTHM",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.rhythm.post_gain","POST GAIN","RHYTHM",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lead.pre_gain","PRE GAIN","LEAD",AmpNativeControlKind::knob,2,{},0.68f,0.f,1.0f},
 {"hw.lead.post_gain","POST GAIN","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.rhythm.bright","BRIGHT","RHYTHM",AmpNativeControlKind::toggle,1,nativeOptions_2_9,0.0f,0.f,1.0f},
 {"hw.rhythm.crunch","CRUNCH","RHYTHM",AmpNativeControlKind::toggle,1,nativeOptions_2_10,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_2[]={"RHYTHM","LEAD"};
inline constexpr const char* nativeChannelKeys_2[]={"rhythm","lead"};
inline constexpr const char* nativeRoutes_2[]={"HIGH GAIN INPUT","LOW GAIN INPUT"};
inline constexpr const char* nativeOptions_3_6[]={"CLEAN","PUSHED"};
inline constexpr const char* nativeOptions_3_13[]={"RAW","VINTAGE","MODERN"};
inline constexpr const char* nativeOptions_3_20[]={"RAW","VINTAGE","MODERN"};
inline constexpr const char* nativeOptions_3_23[]={"BOLD","SPONGY"};
inline constexpr AmpNativeControl nativeControls_3[]={
 {"hw.ch1.gain","GAIN","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.treble","TREBLE","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.mid","MID","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.bass","BASS","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.presence","PRESENCE","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.master","MASTER","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.mode","MODE","CH1",AmpNativeControlKind::choice,1,nativeOptions_3_6,0.0f,0.f,1.0f},
 {"hw.ch2.gain","GAIN","CH2",AmpNativeControlKind::knob,2,{},0.65f,0.f,1.0f},
 {"hw.ch2.treble","TREBLE","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.mid","MID","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.bass","BASS","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.presence","PRESENCE","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.master","MASTER","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.mode","MODE","CH2",AmpNativeControlKind::choice,2,nativeOptions_3_13,1.0f,0.f,2.0f},
 {"hw.ch3.gain","GAIN","CH3",AmpNativeControlKind::knob,4,{},0.68f,0.f,1.0f},
 {"hw.ch3.treble","TREBLE","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.mid","MID","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.bass","BASS","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.presence","PRESENCE","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.master","MASTER","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.mode","MODE","CH3",AmpNativeControlKind::choice,4,nativeOptions_3_20,2.0f,0.f,2.0f},
 {"hw.output","OUTPUT","SHARED OUTPUT",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.solo","SOLO","SHARED OUTPUT",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.power_feel","POWER FEEL","POWER",AmpNativeControlKind::choice,7,nativeOptions_3_23,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_3[]={"CH1","CH2","CH3"};
inline constexpr const char* nativeChannelKeys_3[]={"ch1","ch2","ch3"};
inline constexpr const char* nativeRoutes_3[]={"INPUT"};
inline constexpr const char* nativeOptions_4_10[]={"OFF","ON"};
inline constexpr const char* nativeOptions_4_11[]={"OFF","ON"};
inline constexpr const char* nativeOptions_4_12[]={"OFF","ON"};
inline constexpr const char* nativeOptions_4_20[]={"OFF","ON"};
inline constexpr const char* nativeOptions_4_21[]={"OFF","ON"};
inline constexpr const char* nativeOptions_4_22[]={"OFF","ON"};
inline constexpr const char* nativeOptions_4_28[]={"OFF","ON","AUTO R2"};
inline constexpr const char* nativeOptions_4_30[]={"OFF","ON"};
inline constexpr const char* nativeOptions_4_31[]={"FULL","TWEED"};
inline constexpr const char* nativeOptions_4_32[]={"TRIODE","PENTODE"};
inline constexpr const char* nativeOptions_4_33[]={"SIMUL-CLASS","CLASS A"};
inline constexpr const char* nativeOptions_4_34[]={"HARMONICS","MID GAIN"};
inline constexpr AmpNativeControl nativeControls_4[]={
 {"hw.rhythm.bass","BASS","RHYTHM SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.rhythm.middle","MIDDLE","RHYTHM SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.r1.gain","GAIN","R1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.r1.treble","TREBLE","R1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.r1.presence","PRESENCE","R1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.r1.master","MASTER","R1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.r2.gain","GAIN","R2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.r2.treble","TREBLE","R2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.r2.presence","PRESENCE","R2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.r2.master","MASTER","R2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.r1.bright","GAIN PULL BRIGHT","R1",AmpNativeControlKind::toggle,1,nativeOptions_4_10,0.0f,0.f,1.0f},
 {"hw.r2.fat","GAIN PULL FAT","R2",AmpNativeControlKind::toggle,2,nativeOptions_4_11,0.0f,0.f,1.0f},
 {"hw.r2.presence_shift","PRESENCE PULL SHIFT","R2",AmpNativeControlKind::toggle,2,nativeOptions_4_12,0.0f,0.f,1.0f},
 {"hw.lead.gain","GAIN","LEAD",AmpNativeControlKind::knob,4,{},0.72f,0.f,1.0f},
 {"hw.lead.treble","TREBLE","LEAD",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.lead.bass","BASS","LEAD",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.lead.middle","MIDDLE","LEAD",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.lead.drive","DRIVE","LEAD",AmpNativeControlKind::knob,4,{},0.65f,0.f,1.0f},
 {"hw.lead.presence","PRESENCE","LEAD",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.lead.master","MASTER","LEAD",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.lead.fat","GAIN PULL FAT","LEAD",AmpNativeControlKind::toggle,4,nativeOptions_4_20,0.0f,0.f,1.0f},
 {"hw.lead.bright","DRIVE PULL BRIGHT","LEAD",AmpNativeControlKind::toggle,4,nativeOptions_4_21,0.0f,0.f,1.0f},
 {"hw.lead.presence_shift","PRESENCE PULL SHIFT","LEAD",AmpNativeControlKind::toggle,4,nativeOptions_4_22,0.0f,0.f,1.0f},
 {"hw.geq.80","80 Hz","GRAPHIC EQ",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.geq.240","240 Hz","GRAPHIC EQ",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.geq.750","750 Hz","GRAPHIC EQ",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.geq.2200","2200 Hz","GRAPHIC EQ",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.geq.6600","6600 Hz","GRAPHIC EQ",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.geq.mode","EQ MODE","GRAPHIC EQ",AmpNativeControlKind::choice,7,nativeOptions_4_28,0.0f,0.f,2.0f},
 {"hw.output","OUTPUT LEVEL","SHARED OUTPUT",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.silent_recording","OUTPUT PULL SILENT RECORDING","SHARED OUTPUT",AmpNativeControlKind::toggle,7,nativeOptions_4_30,0.0f,0.f,1.0f},
 {"hw.power","POWER","POWER",AmpNativeControlKind::choice,7,nativeOptions_4_31,0.0f,0.f,1.0f},
 {"hw.triode","OUTPUT TUBES","POWER",AmpNativeControlKind::choice,7,nativeOptions_4_32,0.0f,0.f,1.0f},
 {"hw.class","POWER CLASS","POWER",AmpNativeControlKind::choice,7,nativeOptions_4_33,0.0f,0.f,1.0f},
 {"hw.lead.voicing","LEAD VOICING","POWER",AmpNativeControlKind::choice,4,nativeOptions_4_34,0.0f,0.f,1.0f},
 {"hw.reverb","REVERB","REAR / FX",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_4[]={"RHYTHM 1","RHYTHM 2","LEAD"};
inline constexpr const char* nativeChannelKeys_4[]={"r1","r2","lead"};
inline constexpr const char* nativeRoutes_4[]={"INPUT"};
inline constexpr const char* nativeOptions_5_4[]={"OFF","ON"};
inline constexpr const char* nativeOptions_5_5[]={"1 \u00b7 220 Hz","2 \u00b7 800 Hz","3 \u00b7 3 kHz"};
inline constexpr const char* nativeOptions_5_6[]={"BASS CUT","OFF","ULTRA-LO"};
inline constexpr const char* nativeOptions_5_10[]={"OFF","ON"};
inline constexpr const char* nativeOptions_5_11[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_5[]={
 {"hw.ch1.volume","VOLUME","CHANNEL ONE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.treble","TREBLE","CHANNEL ONE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.midrange","MIDRANGE","CHANNEL ONE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.bass","BASS","CHANNEL ONE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.ultra_hi","ULTRA-HI","CHANNEL ONE",AmpNativeControlKind::toggle,1,nativeOptions_5_4,0.0f,0.f,1.0f},
 {"hw.ch1.mid_frequency","MID FREQUENCY","CHANNEL ONE",AmpNativeControlKind::choice,1,nativeOptions_5_5,0.0f,0.f,2.0f},
 {"hw.ch1.low_mode","LOW MODE","CHANNEL ONE",AmpNativeControlKind::choice,1,nativeOptions_5_6,1.0f,0.f,2.0f},
 {"hw.ch2.volume","VOLUME","CHANNEL TWO",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.treble","TREBLE","CHANNEL TWO",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.bass","BASS","CHANNEL TWO",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.ultra_hi","ULTRA-HI","CHANNEL TWO",AmpNativeControlKind::toggle,2,nativeOptions_5_10,0.0f,0.f,1.0f},
 {"hw.ch2.ultra_lo","ULTRA-LO","CHANNEL TWO",AmpNativeControlKind::toggle,2,nativeOptions_5_11,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_5[]={"CHANNEL ONE","CHANNEL TWO"};
inline constexpr const char* nativeChannelKeys_5[]={"ch1","ch2"};
inline constexpr const char* nativeRoutes_5[]={"NORMAL INPUT","BRIGHT INPUT"};
inline constexpr const char* nativeOptions_6_6[]={"OFF","ON"};
inline constexpr const char* nativeOptions_6_7[]={"OFF","ON"};
inline constexpr const char* nativeOptions_6_8[]={"OFF","ON"};
inline constexpr const char* nativeOptions_6_9[]={"OFF","ON"};
inline constexpr const char* nativeOptions_6_13[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_6[]={
 {"hw.volume","VOLUME","INPUT / EQ",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","INPUT / EQ",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.hi_mid","HI MID","INPUT / EQ",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lo_mid","LO MID","INPUT / EQ",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.bass","BASS","INPUT / EQ",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.boost","BOOST","INPUT / EQ",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.pad","INPUT -10 dB","INPUT / EQ",AmpNativeControlKind::toggle,1,nativeOptions_6_6,0.0f,0.f,1.0f},
 {"hw.low_cut","LOW CUT","VOICING",AmpNativeControlKind::toggle,1,nativeOptions_6_7,0.0f,0.f,1.0f},
 {"hw.mid_cut","MID CUT","VOICING",AmpNativeControlKind::toggle,1,nativeOptions_6_8,0.0f,0.f,1.0f},
 {"hw.high_boost","HIGH BOOST","VOICING",AmpNativeControlKind::toggle,1,nativeOptions_6_9,0.0f,0.f,1.0f},
 {"hw.low_master","LOW MASTER","BI-AMP TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.high_master","HIGH MASTER","BI-AMP TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.crossover","CROSSOVER","BI-AMP TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.biamp","BI-AMP","BI-AMP TARGET",AmpNativeControlKind::toggle,1,nativeOptions_6_13,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_6[]={"SINGLE"};
inline constexpr const char* nativeChannelKeys_6[]={"single"};
inline constexpr const char* nativeRoutes_6[]={"INPUT"};
inline constexpr const char* nativeOptions_7_8[]={"CUT","FLAT","BOOST"};
inline constexpr const char* nativeOptions_7_9[]={"CUT","FLAT","BOOST"};
inline constexpr const char* nativeOptions_7_10[]={"250 Hz","500 Hz","1 kHz"};
inline constexpr const char* nativeOptions_7_11[]={"750 Hz","1.5 kHz","3 kHz"};
inline constexpr const char* nativeOptions_7_12[]={"OFF","ON"};
inline constexpr const char* nativeOptions_7_18[]={"OFF","ON"};
inline constexpr const char* nativeOptions_7_19[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_7[]={
 {"hw.b7k.master","MASTER","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.blend","BLEND","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.level","LEVEL","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.drive","DRIVE","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.bass","BASS","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.lo_mids","LO MIDS","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.hi_mids","HI MIDS","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.treble","TREBLE","B7K ULTRA",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.b7k.attack","ATTACK","B7K ULTRA",AmpNativeControlKind::choice,1,nativeOptions_7_8,1.0f,0.f,2.0f},
 {"hw.b7k.grunt","GRUNT","B7K ULTRA",AmpNativeControlKind::choice,1,nativeOptions_7_9,1.0f,0.f,2.0f},
 {"hw.b7k.lo_frequency","LO MID FREQ","B7K ULTRA",AmpNativeControlKind::choice,1,nativeOptions_7_10,0.0f,0.f,2.0f},
 {"hw.b7k.hi_frequency","HI MID FREQ","B7K ULTRA",AmpNativeControlKind::choice,1,nativeOptions_7_11,0.0f,0.f,2.0f},
 {"hw.b7k.distortion","DISTORTION","B7K ULTRA",AmpNativeControlKind::toggle,1,nativeOptions_7_12,0.0f,0.f,1.0f},
 {"hw.db751.gain","GAIN","DB751 TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.db751.bass","BASS","DB751 TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.db751.mid","MID","DB751 TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.db751.treble","TREBLE","DB751 TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.db751.master","MASTER","DB751 TARGET",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.db751.deep","DEEP","DB751 TARGET",AmpNativeControlKind::toggle,1,nativeOptions_7_18,0.0f,0.f,1.0f},
 {"hw.db751.bright","BRIGHT","DB751 TARGET",AmpNativeControlKind::toggle,1,nativeOptions_7_19,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_7[]={"SINGLE"};
inline constexpr const char* nativeChannelKeys_7[]={"single"};
inline constexpr const char* nativeRoutes_7[]={"INPUT"};
inline constexpr AmpNativeControl nativeControls_8[]={
 {"hw.normal.volume","VOLUME","NORMAL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.top_boost.volume","VOLUME","TOP BOOST",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.top_boost.treble","TREBLE","TOP BOOST",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.top_boost.bass","BASS","TOP BOOST",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.tone_cut","TONE CUT","MASTER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.master_volume","MASTER VOLUME","MASTER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.reverb_tone","REVERB TONE","ONBOARD FX",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.reverb_level","REVERB LEVEL","ONBOARD FX",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.tremolo_speed","TREMOLO SPEED","ONBOARD FX",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.tremolo_depth","TREMOLO DEPTH","ONBOARD FX",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_8[]={"NORMAL","TOP BOOST"};
inline constexpr const char* nativeChannelKeys_8[]={"normal","top_boost"};
inline constexpr const char* nativeRoutes_8[]={"HIGH INPUT","LOW INPUT"};
inline constexpr const char* nativeOptions_9_10[]={"FULL","HALF"};
inline constexpr AmpNativeControl nativeControls_9[]={
 {"hw.clean.volume","VOLUME","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.treble","TREBLE","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.bass","BASS","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.dirty.gain","GAIN","DIRTY",AmpNativeControlKind::knob,2,{},0.66f,0.f,1.0f},
 {"hw.dirty.treble","TREBLE","DIRTY",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.dirty.middle","MIDDLE","DIRTY",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.dirty.bass","BASS","DIRTY",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.dirty.volume","VOLUME","DIRTY",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.reverb","REVERB","GLOBAL",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.attenuator","ATTENUATOR","GLOBAL",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.power","POWER","POWER",AmpNativeControlKind::choice,3,nativeOptions_9_10,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_9[]={"CLEAN","DIRTY"};
inline constexpr const char* nativeChannelKeys_9[]={"clean","dirty"};
inline constexpr const char* nativeRoutes_9[]={"INPUT"};
inline constexpr const char* nativeOptions_10_11[]={"OFF","ON"};
inline constexpr const char* nativeOptions_10_12[]={"OFF","ON"};
inline constexpr const char* nativeOptions_10_13[]={"OFF","ON"};
inline constexpr const char* nativeOptions_10_14[]={"OFF","ON"};
inline constexpr const char* nativeOptions_10_16[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_10[]={
 {"hw.vintage.volume","VOLUME","VINTAGE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.vintage.bass","BASS","VINTAGE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.vintage.mid","MID","VINTAGE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.vintage.treble","TREBLE","VINTAGE",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.overdrive.gain","GAIN","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.overdrive.blend","BLEND","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.overdrive.volume","VOLUME","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.overdrive.bass","BASS","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.overdrive.mid_frequency","MID FREQUENCY","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.overdrive.mid_level","MID LEVEL","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.overdrive.treble","TREBLE","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.vintage.deep","BASS PULL DEEP","VINTAGE",AmpNativeControlKind::toggle,1,nativeOptions_10_11,0.0f,0.f,1.0f},
 {"hw.vintage.bright","TREBLE PULL BRIGHT","VINTAGE",AmpNativeControlKind::toggle,1,nativeOptions_10_12,0.0f,0.f,1.0f},
 {"hw.overdrive.deep","BASS PULL DEEP","OVERDRIVE",AmpNativeControlKind::toggle,2,nativeOptions_10_13,0.0f,0.f,1.0f},
 {"hw.overdrive.bright","TREBLE PULL BRIGHT","OVERDRIVE",AmpNativeControlKind::toggle,2,nativeOptions_10_14,0.0f,0.f,1.0f},
 {"hw.master","MASTER","GLOBAL",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.mute","MASTER PULL MUTE","GLOBAL",AmpNativeControlKind::toggle,3,nativeOptions_10_16,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_10[]={"VINTAGE","OVERDRIVE"};
inline constexpr const char* nativeChannelKeys_10[]={"vintage","overdrive"};
inline constexpr const char* nativeRoutes_10[]={"INPUT 1","INPUT 2 \u00b7 -6 dB"};
inline constexpr const char* nativeOptions_11_10[]={"OFF","ON"};
inline constexpr const char* nativeOptions_11_11[]={"OFF","ON"};
inline constexpr const char* nativeOptions_11_12[]={"OFF","ON"};
inline constexpr const char* nativeOptions_11_13[]={"PASSIVE","ACTIVE"};
inline constexpr AmpNativeControl nativeControls_11[]={
 {"hw.input","INPUT","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.high_pass","HIGH PASS","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.voicing","VOICING","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.bass","BASS","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lo_mid_frequency","LO MID FREQUENCY","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lo_mid","LO MID","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.hi_mid_frequency","HI MID FREQUENCY","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.hi_mid","HI MID","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.deep","DEEP","PANEL",AmpNativeControlKind::toggle,1,nativeOptions_11_10,0.0f,0.f,1.0f},
 {"hw.bright","BRIGHT","PANEL",AmpNativeControlKind::toggle,1,nativeOptions_11_11,0.0f,0.f,1.0f},
 {"hw.mute","MUTE","PANEL",AmpNativeControlKind::toggle,1,nativeOptions_11_12,0.0f,0.f,1.0f},
 {"hw.input_type","INPUT TYPE","PANEL",AmpNativeControlKind::choice,1,nativeOptions_11_13,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_11[]={"SINGLE"};
inline constexpr const char* nativeChannelKeys_11[]={"single"};
inline constexpr const char* nativeRoutes_11[]={"INPUT"};
inline constexpr const char* nativeOptions_12_4[]={"1","2","3","4","5","6"};
inline constexpr const char* nativeOptions_12_7[]={"OFF","ON"};
inline constexpr const char* nativeOptions_12_8[]={"HI","LO"};
inline constexpr AmpNativeControl nativeControls_12[]={
 {"hw.ch1.volume","VOLUME","CH1 / 12AX7",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.bass","BASS","CH1 / 12AX7",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.treble","TREBLE","CH1 / 12AX7",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch2.volume","VOLUME","CH2 / EF86",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.tone","TONE","CH2 / EF86",AmpNativeControlKind::choice,2,nativeOptions_12_4,0.0f,0.f,5.0f},
 {"hw.cut","CUT","MASTER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER VOLUME","MASTER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.master_bypass","MASTER BYPASS","MASTER",AmpNativeControlKind::toggle,3,nativeOptions_12_7,0.0f,0.f,1.0f},
 {"hw.power","POWER","POWER",AmpNativeControlKind::choice,3,nativeOptions_12_8,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_12[]={"CH1 / 12AX7","CH2 / EF86"};
inline constexpr const char* nativeChannelKeys_12[]={"ch1","ch2"};
inline constexpr const char* nativeRoutes_12[]={"HIGH INPUT","LOW INPUT"};
inline constexpr const char* nativeOptions_13_6[]={"OFF","ON"};
inline constexpr const char* nativeOptions_13_7[]={"ROCK","JAZZ"};
inline constexpr const char* nativeOptions_13_10[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_13[]={
 {"hw.volume","VOLUME","SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.middle","MIDDLE","SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.bass","BASS","SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.presence","PRESENCE","SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.bright","BRIGHT","SHARED",AmpNativeControlKind::toggle,3,nativeOptions_13_6,0.0f,0.f,1.0f},
 {"hw.voicing","VOICING","SHARED",AmpNativeControlKind::choice,3,nativeOptions_13_7,0.0f,0.f,1.0f},
 {"hw.od.drive","DRIVE","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.od.ratio","RATIO","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.pab","PREAMP BOOST","SHARED",AmpNativeControlKind::toggle,3,nativeOptions_13_10,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_13[]={"CLEAN","OVERDRIVE"};
inline constexpr const char* nativeChannelKeys_13[]={"clean","od"};
inline constexpr const char* nativeRoutes_13[]={"INPUT"};
inline constexpr const char* nativeOptions_14_7[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_14[]={
 {"hw.gain","GAIN","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.taste","TASTE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lo","LO","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lo_mid","LO MID","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.hi_mid","HI MID","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.hi","HI","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.mute","MUTE","PANEL",AmpNativeControlKind::toggle,1,nativeOptions_14_7,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_14[]={"SINGLE"};
inline constexpr const char* nativeChannelKeys_14[]={"single"};
inline constexpr const char* nativeRoutes_14[]={"INPUT"};
inline constexpr const char* nativeOptions_15_5[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_6[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_7[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_8[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_14[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_15[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_16[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_17[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_23[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_24[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_25[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_26[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_32[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_33[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_34[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_35[]={"OFF","ON"};
inline constexpr const char* nativeOptions_15_41[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_15[]={
 {"ch1.gain","GAIN","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"ch1.volume","VOLUME","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"ch1.low","LOW","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"ch1.mid","MID","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"ch1.high","HIGH","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"ch1.low_cut","LOW CUT","CH1",AmpNativeControlKind::toggle,1,nativeOptions_15_5,0.0f,0.f,1.0f},
 {"ch1.gain_switch","GAIN SWITCH","CH1",AmpNativeControlKind::toggle,1,nativeOptions_15_6,0.0f,0.f,1.0f},
 {"ch1.gate","GATE","CH1",AmpNativeControlKind::toggle,1,nativeOptions_15_7,0.0f,0.f,1.0f},
 {"ch1.bright","BRIGHT","CH1",AmpNativeControlKind::toggle,1,nativeOptions_15_8,0.0f,0.f,1.0f},
 {"ch2.gain","GAIN","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"ch2.volume","VOLUME","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"ch2.low","LOW","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"ch2.mid","MID","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"ch2.high","HIGH","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"ch2.vintage","VINTAGE","CH2",AmpNativeControlKind::toggle,2,nativeOptions_15_14,0.0f,0.f,1.0f},
 {"ch2.gain_switch","GAIN SWITCH","CH2",AmpNativeControlKind::toggle,2,nativeOptions_15_15,0.0f,0.f,1.0f},
 {"ch2.gate","GATE","CH2",AmpNativeControlKind::toggle,2,nativeOptions_15_16,0.0f,0.f,1.0f},
 {"ch2.bright","BRIGHT","CH2",AmpNativeControlKind::toggle,2,nativeOptions_15_17,0.0f,0.f,1.0f},
 {"ch3.gain","GAIN","CH3",AmpNativeControlKind::knob,4,{},0.78f,0.f,1.0f},
 {"ch3.volume","VOLUME","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"ch3.low","LOW","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"ch3.mid","MID","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"ch3.high","HIGH","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"ch3.vintage","VINTAGE","CH3",AmpNativeControlKind::toggle,4,nativeOptions_15_23,0.0f,0.f,1.0f},
 {"ch3.gain_switch","GAIN SWITCH","CH3",AmpNativeControlKind::toggle,4,nativeOptions_15_24,0.0f,0.f,1.0f},
 {"ch3.gate","GATE","CH3",AmpNativeControlKind::toggle,4,nativeOptions_15_25,0.0f,0.f,1.0f},
 {"ch3.bright","BRIGHT","CH3",AmpNativeControlKind::toggle,4,nativeOptions_15_26,0.0f,0.f,1.0f},
 {"ch4.gain","GAIN","CH4",AmpNativeControlKind::knob,8,{},0.68f,0.f,1.0f},
 {"ch4.volume","VOLUME","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"ch4.low","LOW","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"ch4.mid","MID","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"ch4.high","HIGH","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"ch4.low_boost","LOW BOOST","CH4",AmpNativeControlKind::toggle,8,nativeOptions_15_32,0.0f,0.f,1.0f},
 {"ch4.tight","TIGHT","CH4",AmpNativeControlKind::toggle,8,nativeOptions_15_33,0.0f,0.f,1.0f},
 {"ch4.gate","GATE","CH4",AmpNativeControlKind::toggle,8,nativeOptions_15_34,0.0f,0.f,1.0f},
 {"ch4.mid_boost","MID BOOST","CH4",AmpNativeControlKind::toggle,8,nativeOptions_15_35,0.0f,0.f,1.0f},
 {"presence","PRESENCE","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
 {"depth","DEPTH","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
 {"master","MASTER","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
 {"gate_threshold","GATE THRESHOLD","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
 {"solo_level","SOLO LEVEL","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
 {"presence_frequency_shift","PRESENCE FREQUENCY SHIFT","GLOBAL",AmpNativeControlKind::toggle,15,nativeOptions_15_41,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_15[]={"CH1","CH2","CH3","CH4"};
inline constexpr const char* nativeChannelKeys_15[]={"ch1","ch2","ch3","ch4"};
inline constexpr const char* nativeRoutes_15[]={"INPUT"};
inline constexpr const char* nativeOptions_16_9[]={"OFF","ON"};
inline constexpr const char* nativeOptions_16_10[]={"OFF","ON"};
inline constexpr const char* nativeOptions_16_11[]={"FULL","5 W","1 W","SPEAKER OFF"};
inline constexpr AmpNativeControl nativeControls_16[]={
 {"hw.clean.gain","CLEAN GAIN","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lead.gain","LEAD GAIN","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.lead.volume","LEAD VOLUME","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.bass","BASS","SHARED EQ",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.middle","MIDDLE","SHARED EQ",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","SHARED EQ",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.presence","LEAD PRESENCE","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","GLOBAL",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.reverb","REVERB","GLOBAL",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.gain_boost","GAIN BOOST","GLOBAL",AmpNativeControlKind::toggle,3,nativeOptions_16_9,0.0f,0.f,1.0f},
 {"hw.mvb","MASTER VOLUME BOOST","GLOBAL",AmpNativeControlKind::toggle,3,nativeOptions_16_10,0.0f,0.f,1.0f},
 {"hw.power_soak","POWER SOAK","POWER",AmpNativeControlKind::choice,3,nativeOptions_16_11,0.0f,0.f,3.0f},
};
inline constexpr const char* nativeChannels_16[]={"CLEAN","LEAD"};
inline constexpr const char* nativeChannelKeys_16[]={"clean","lead"};
inline constexpr const char* nativeRoutes_16[]={"INPUT"};
inline constexpr AmpNativeControl nativeControls_17[]={
 {"hw.ch1.gain","GAIN","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.treble","TREBLE","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.middle","MIDDLE","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.bass","BASS","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch1.volume","VOLUME","CH1",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ch2.gain","GAIN","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.treble","TREBLE","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.middle","MIDDLE","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.bass","BASS","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch2.volume","VOLUME","CH2",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.ch3.gain","GAIN","CH3",AmpNativeControlKind::knob,4,{},0.78f,0.f,1.0f},
 {"hw.ch3.treble","TREBLE","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.middle","MIDDLE","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.bass","BASS","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch3.volume","VOLUME","CH3",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.ch4.gain","GAIN","CH4",AmpNativeControlKind::knob,8,{},0.72f,0.f,1.0f},
 {"hw.ch4.treble","TREBLE","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"hw.ch4.middle","MIDDLE","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"hw.ch4.bass","BASS","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"hw.ch4.volume","VOLUME","CH4",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
 {"hw.presence","PRESENCE","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
 {"hw.deep","DEEP","GLOBAL",AmpNativeControlKind::knob,15,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_17[]={"CH1 / CLEAN","CH2 / CRUNCH","CH3 / MEGA","CH4 / LEAD"};
inline constexpr const char* nativeChannelKeys_17[]={"ch1","ch2","ch3","ch4"};
inline constexpr const char* nativeRoutes_17[]={"INPUT"};
inline constexpr const char* nativeOptions_18_5[]={"1","2","3","4","5"};
inline constexpr const char* nativeOptions_18_6[]={"OFF","ON"};
inline constexpr const char* nativeOptions_18_7[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_18[]={
 {"hw.gain","GAIN","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.bass","BASS","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.midrange","MIDRANGE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.mid_frequency","FREQUENCY","PANEL",AmpNativeControlKind::choice,1,nativeOptions_18_5,0.0f,0.f,4.0f},
 {"hw.ultra_hi","ULTRA HI","PANEL",AmpNativeControlKind::toggle,1,nativeOptions_18_6,0.0f,0.f,1.0f},
 {"hw.ultra_lo","ULTRA LO","PANEL",AmpNativeControlKind::toggle,1,nativeOptions_18_7,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_18[]={"SINGLE"};
inline constexpr const char* nativeChannelKeys_18[]={"single"};
inline constexpr const char* nativeRoutes_18[]={"INPUT"};
inline constexpr AmpNativeControl nativeControls_19[]={
 {"hw.normal","NORMAL","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.brilliant","BRILLIANT","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.bass","BASS","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.midrange","MIDRANGE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","PANEL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_19[]={"SINGLE"};
inline constexpr const char* nativeChannelKeys_19[]={"single"};
inline constexpr const char* nativeRoutes_19[]={"NORMAL","BRILLIANT","JUMPED"};
inline constexpr const char* nativeOptions_20_17[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_20[]={
 {"hw.ep.girth","GIRTH","EVIL PUMPKIN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ep.grind","GRIND","EVIL PUMPKIN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.ep.gain","GAIN","EVIL PUMPKIN",AmpNativeControlKind::knob,1,{},0.72f,0.f,1.0f},
 {"hw.kk.gain1","GAIN 1","KILLER KALI",AmpNativeControlKind::knob,2,{},0.68f,0.f,1.0f},
 {"hw.kk.gain2","GAIN 2","KILLER KALI",AmpNativeControlKind::knob,2,{},0.62f,0.f,1.0f},
 {"hw.gain_eq.bass","BASS","GAIN CHANNELS SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.gain_eq.middle","MIDDLE","GAIN CHANNELS SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.gain_eq.sweep","SWEEP","GAIN CHANNELS SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.gain_eq.treble","TREBLE","GAIN CHANNELS SHARED",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.clean.volume","VOLUME","CLEAN",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.clean.bass","BASS","CLEAN",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.clean.middle","MIDDLE","CLEAN",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.clean.treble","TREBLE","CLEAN",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.depth","DEPTH","GLOBAL",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.presence","PRESENCE","GLOBAL",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.master1","MASTER 1","GLOBAL",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.master2","MASTER 2","GLOBAL",AmpNativeControlKind::knob,7,{},0.5f,0.f,1.0f},
 {"hw.master2_select","MASTER 2 SELECT","GLOBAL",AmpNativeControlKind::toggle,7,nativeOptions_20_17,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_20[]={"GAIN I","GAIN II","CLEAN"};
inline constexpr const char* nativeChannelKeys_20[]={"ep","kk","clean"};
inline constexpr const char* nativeRoutes_20[]={"INPUT"};
inline constexpr const char* nativeOptions_21_4[]={"OFF","ON"};
inline constexpr const char* nativeOptions_21_5[]={"CLEAN","CRUNCH"};
inline constexpr AmpNativeControl nativeControls_21[]={
 {"hw.normal.preamp","PREAMP","NORMAL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.normal.master","MASTER","NORMAL",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.overdrive.preamp","PREAMP","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.72f,0.f,1.0f},
 {"hw.overdrive.master","MASTER","OVERDRIVE",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.normal.bright","BRIGHT","NORMAL",AmpNativeControlKind::toggle,1,nativeOptions_21_4,0.0f,0.f,1.0f},
 {"hw.normal.mode","NORMAL MODE","NORMAL",AmpNativeControlKind::choice,1,nativeOptions_21_5,0.0f,0.f,1.0f},
 {"hw.bass","BASS","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.middle","MIDDLE","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.treble","TREBLE","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.presence","PRESENCE","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.depth","DEPTH","SHARED EQ / POWER",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_21[]={"NORMAL","OVERDRIVE"};
inline constexpr const char* nativeChannelKeys_21[]={"normal","overdrive"};
inline constexpr const char* nativeRoutes_21[]={"INPUT"};
inline constexpr AmpNativeControl nativeControls_22[]={
 {"hw.clean.gain","GAIN","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.bass","BASS","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.middle","MIDDLE","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.treble","TREBLE","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.volume","VOLUME","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.lead.gain","GAIN","LEAD",AmpNativeControlKind::knob,2,{},0.7f,0.f,1.0f},
 {"hw.lead.bass","BASS","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.lead.middle","MIDDLE","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.lead.treble","TREBLE","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.lead.presence","PRESENCE","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.lead.volume","VOLUME","LEAD",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.master","MASTER","GLOBAL",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_22[]={"CLEAN","LEAD"};
inline constexpr const char* nativeChannelKeys_22[]={"clean","lead"};
inline constexpr const char* nativeRoutes_22[]={"INPUT"};
inline constexpr const char* nativeOptions_23_16[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_17[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_18[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_19[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_20[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_21[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_22[]={"MODERN","CLASSIC"};
inline constexpr const char* nativeOptions_23_25[]={"A","B"};
inline constexpr const char* nativeOptions_23_28[]={"A","B"};
inline constexpr const char* nativeOptions_23_29[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_30[]={"OFF","ON"};
inline constexpr const char* nativeOptions_23_31[]={"OFF","ON"};
inline constexpr AmpNativeControl nativeControls_23[]={
 {"hw.clean.gain","GAIN","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.treble","TREBLE","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.clean.volume","VOLUME","CLEAN",AmpNativeControlKind::knob,1,{},0.5f,0.f,1.0f},
 {"hw.crunch.gain","GAIN","CRUNCH",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.crunch.treble","TREBLE","CRUNCH",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.crunch.volume","VOLUME","CRUNCH",AmpNativeControlKind::knob,2,{},0.5f,0.f,1.0f},
 {"hw.lead1.gain","GAIN","LEAD I",AmpNativeControlKind::knob,4,{},0.72f,0.f,1.0f},
 {"hw.lead1.treble","TREBLE","LEAD I",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.lead1.volume","VOLUME","LEAD I",AmpNativeControlKind::knob,4,{},0.5f,0.f,1.0f},
 {"hw.lead2.gain","GAIN","LEAD II",AmpNativeControlKind::knob,8,{},0.68f,0.f,1.0f},
 {"hw.lead2.treble","TREBLE","LEAD II",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"hw.lead2.volume","VOLUME","LEAD II",AmpNativeControlKind::knob,8,{},0.5f,0.f,1.0f},
 {"hw.clean_eq.bass","BASS","CLEAN / CRUNCH EQ",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.clean_eq.middle","MIDDLE","CLEAN / CRUNCH EQ",AmpNativeControlKind::knob,3,{},0.5f,0.f,1.0f},
 {"hw.lead_eq.bass","BASS","LEAD EQ",AmpNativeControlKind::knob,12,{},0.5f,0.f,1.0f},
 {"hw.lead_eq.middle","MIDDLE","LEAD EQ",AmpNativeControlKind::knob,12,{},0.5f,0.f,1.0f},
 {"hw.gain_boost","GAIN BOOST","VOICING",AmpNativeControlKind::toggle,3,nativeOptions_23_16,0.0f,0.f,1.0f},
 {"hw.mid_shift","MID SHIFT","VOICING",AmpNativeControlKind::toggle,3,nativeOptions_23_17,0.0f,0.f,1.0f},
 {"hw.bright","BRIGHT","VOICING",AmpNativeControlKind::toggle,3,nativeOptions_23_18,0.0f,0.f,1.0f},
 {"hw.hi_gain","HI GAIN","VOICING",AmpNativeControlKind::toggle,12,nativeOptions_23_19,1.0f,0.f,1.0f},
 {"hw.contour","CONTOUR","VOICING",AmpNativeControlKind::toggle,12,nativeOptions_23_20,0.0f,0.f,1.0f},
 {"hw.mid_edge","MID EDGE","VOICING",AmpNativeControlKind::toggle,12,nativeOptions_23_21,0.0f,0.f,1.0f},
 {"hw.character","CHARACTER","VOICING",AmpNativeControlKind::choice,15,nativeOptions_23_22,0.0f,0.f,1.0f},
 {"hw.presence_a","PRESENCE A","POWER",AmpNativeControlKind::knob,31,{},0.5f,0.f,1.0f},
 {"hw.presence_b","PRESENCE B","POWER",AmpNativeControlKind::knob,31,{},0.5f,0.f,1.0f},
 {"hw.presence_select","PRESENCE","POWER",AmpNativeControlKind::choice,31,nativeOptions_23_25,0.0f,0.f,1.0f},
 {"hw.master_a","MASTER A","POWER",AmpNativeControlKind::knob,31,{},0.5f,0.f,1.0f},
 {"hw.master_b","MASTER B","POWER",AmpNativeControlKind::knob,31,{},0.5f,0.f,1.0f},
 {"hw.master_select","MASTER","POWER",AmpNativeControlKind::choice,31,nativeOptions_23_28,0.0f,0.f,1.0f},
 {"hw.depth_boost","DEPTH BOOST","POWER",AmpNativeControlKind::toggle,31,nativeOptions_23_29,0.0f,0.f,1.0f},
 {"hw.mega_lo_punch","MEGA LO PUNCH","VOICING",AmpNativeControlKind::toggle,15,nativeOptions_23_30,0.0f,0.f,1.0f},
 {"hw.tube_eq","T.D. EQ","TUBE DRIVER",AmpNativeControlKind::toggle,16,nativeOptions_23_31,0.0f,0.f,1.0f},
};
inline constexpr const char* nativeChannels_23[]={"CLEAN","CRUNCH","LEAD I","LEAD II","TUBE DRIVER"};
inline constexpr const char* nativeChannelKeys_23[]={"clean","crunch","lead1","lead2","driver"};
inline constexpr const char* nativeRoutes_23[]={"INPUT"};
inline constexpr auto nativeOriginalControls=[] {
    std::array<AmpNativeControl,original::controlCount> result{};
    for(size_t i=0;i<result.size();++i){const auto& c=original::controls[i];result[i]={c.id,c.label,i<8?"AMPLIFIER":"CHARACTER",AmpNativeControlKind::knob,31,{},original::channelState(0).values[i],c.minimum,c.maximum};}
    return result;
}();
inline constexpr auto& nativeOriginalChannels=original::channelNames;
inline constexpr auto& nativeOriginalKeys=original::channelKeys;
inline constexpr const char* nativeOriginalRoutes[]={"INPUT"};
inline constexpr std::array<AmpNativePanel,ampModelCount> ampNativePanels{{
 {"Fender '65 Twin Reverb reissue","primary_core_reviewed",nativeControls_0,nativeChannels_0,nativeChannelKeys_0,nativeRoutes_0,0},
 {"Marshall JTM45 2245 reissue","primary_core_reviewed",nativeControls_1,nativeChannels_1,nativeChannelKeys_1,nativeRoutes_1,0},
 {"Peavey 6505 1992 Original \u2014 not 6505 II/Plus","primary_core_reviewed",nativeControls_2,nativeChannels_2,nativeChannelKeys_2,nativeRoutes_2,1},
 {"Mesa Dual Rectifier \u2014 three-channel core / Multi-Watt revision pending","partial_primary_review",nativeControls_3,nativeChannels_3,nativeChannelKeys_3,nativeRoutes_3,2},
 {"Mesa Mark IV \u2014 manual panel / Lead reference","primary_core_reviewed",nativeControls_4,nativeChannels_4,nativeChannelKeys_4,nativeRoutes_4,2},
 {"Ampeg SVT-VR","primary_core_reviewed",nativeControls_5,nativeChannels_5,nativeChannelKeys_5,nativeRoutes_5,0},
 {"Gallien-Krueger 800RB \u2014 bi-amp original","partial_primary_review",nativeControls_6,nativeChannels_6,nativeChannelKeys_6,nativeRoutes_6,0},
 {"Darkglass B7K Ultra + Aguilar DB751 \u2014 reference chain","partial_primary_review",nativeControls_7,nativeChannels_7,nativeChannelKeys_7,nativeRoutes_7,0},
 {"VOX AC30CH Custom Head","primary_core_reviewed",nativeControls_8,nativeChannels_8,nativeChannelKeys_8,nativeRoutes_8,1},
 {"Orange Rockerverb 50 MKIII \u2014 target panel","primary_panel_pending",nativeControls_9,nativeChannels_9,nativeChannelKeys_9,nativeRoutes_9,1},
 {"Fender Super Bassman","primary_core_reviewed",nativeControls_10,nativeChannels_10,nativeChannelKeys_10,nativeRoutes_10,1},
 {"Mesa Subway D-800+ \u2014 not D-800","primary_panel_pending",nativeControls_11,nativeChannels_11,nativeChannelKeys_11,nativeRoutes_11,0},
 {"Matchless C-30 / DC-30 \u2014 original panel target","primary_core_reviewed",nativeControls_12,nativeChannels_12,nativeChannelKeys_12,nativeRoutes_12,1},
 {"ODS #102-style clone \u2014 exact hardware/panel pending","primary_panel_pending",nativeControls_13,nativeChannels_13,nativeChannelKeys_13,nativeRoutes_13,1},
 {"EICH T900","primary_core_reviewed",nativeControls_14,nativeChannels_14,nativeChannelKeys_14,nativeRoutes_14,0},
 {"ZUTA GBG120","primary_core_reviewed",nativeControls_15,nativeChannels_15,nativeChannelKeys_15,nativeRoutes_15,2},
 {"ENGL Ironball E606 20W \u2014 proposed exact model","primary_core_reviewed",nativeControls_16,nativeChannels_16,nativeChannelKeys_16,nativeRoutes_16,1},
 {"Diezel VH4 \u2014 core channel controls","partial_primary_review",nativeControls_17,nativeChannels_17,nativeChannelKeys_17,nativeRoutes_17,2},
 {"Ampeg SVT-CL \u2014 stock classic target","partial_primary_review",nativeControls_18,nativeChannels_18,nativeChannelKeys_18,nativeRoutes_18,0},
 {"SUNN Model T \u2014 1970s target, revision unresolved","primary_panel_pending",nativeControls_19,nativeChannels_19,nativeChannelKeys_19,nativeRoutes_19,0},
 {"Fortin Evil Pumpkin \u2014 2023 panel","partial_primary_review",nativeControls_20,nativeChannels_20,nativeChannelKeys_20,nativeRoutes_20,0},
 {"Soldano SLO-100 Classic panel target / LTD capture revision pending","partial_primary_review",nativeControls_21,nativeChannels_21,nativeChannelKeys_21,nativeRoutes_21,1},
 {"Bogner Uberschall Rev Blue \u2014 target panel","primary_panel_pending",nativeControls_22,nativeChannels_22,nativeChannelKeys_22,nativeRoutes_22,1},
 {"ENGL E670FE Special Edition Founders Edition","partial_primary_review",nativeControls_23,nativeChannels_23,nativeChannelKeys_23,nativeRoutes_23,2},
 {"SpectralForge Original","authored_reference_informed",nativeOriginalControls,nativeOriginalChannels,nativeOriginalKeys,nativeOriginalRoutes,0},
}};
inline const AmpNativePanel& ampNativePanel(int model) noexcept { return ampNativePanels[(size_t)juce::jlimit(0,ampModelCount-1,model)]; }
inline int ampNativeContext(int mode,int lane) noexcept { return mode==0?0:mode==1?1+juce::jlimit(0,1,lane):3+juce::jlimit(0,2,lane); }
inline bool ampNativeControlVisible(int model,int control,int channel) noexcept { const auto& p=ampNativePanel(model); return control>=0 && control<(int)p.controls.size() && channel>=0 && channel<(int)p.channels.size() && (p.controls[(size_t)control].channelMask & (1u<<channel))!=0; }
struct AmpNativeState { bool enabled{},soloEnabled{},originalModern{true}; int model{},channel{},inputRoute{}; float inputTrimDb{},outputLevelDb{}; std::array<float,maxAmpNativeControls> values{}; bool operator==(const AmpNativeState&) const = default; };
inline AmpNativeState defaultAmpNativeState(int model) noexcept { AmpNativeState s; s.enabled=true;s.model=juce::jlimit(0,ampModelCount-1,model);const auto& p=ampNativePanel(s.model);s.channel=p.defaultChannel;for(size_t c=0;c<p.controls.size();++c)s.values[c]=p.controls[c].initial;return s; }
inline void sanitiseAmpNativeState(AmpNativeState& s) noexcept { s.inputTrimDb=std::isfinite(s.inputTrimDb)?juce::jlimit(-24.f,24.f,s.inputTrimDb):0.f;s.outputLevelDb=std::isfinite(s.outputLevelDb)?juce::jlimit(-24.f,24.f,s.outputLevelDb):0.f;s.model=juce::jlimit(0,ampModelCount-1,s.model);const auto& p=ampNativePanel(s.model);s.channel=juce::jlimit(0,(int)p.channels.size()-1,s.channel);s.inputRoute=juce::jlimit(0,(int)p.routes.size()-1,s.inputRoute);for(size_t c=0;c<p.controls.size();++c){const auto& k=p.controls[c];auto& v=s.values[c];v=std::isfinite(v)?juce::jlimit(k.minimum,k.maximum,v):k.initial;if(k.kind!=AmpNativeControlKind::knob)v=std::round(v);}}
inline int ampNativeControlIndex(int model,std::string_view key) noexcept { const auto& p=ampNativePanel(model);for(size_t i=0;i<p.controls.size();++i)if(key==p.controls[i].key)return(int)i;return -1; }
inline float ampNativeValue(const AmpNativeState& s,std::string_view key,float fallback=.5f) noexcept { const int i=ampNativeControlIndex(s.model,key);return i>=0?s.values[(size_t)i]:fallback; }
} // namespace spectralforge
