#pragma once
#include <juce_dsp/juce_dsp.h>
#include <array>
#include <cmath>
namespace spectralforge {
enum class RoutingMode:int{classic,dual,matrix};
enum class AmpModel:int{glass,britEdge,tight515,wideRect,liquidLead,ironTube,solidPunch,modernBass};
struct LaneState{int amp{};float drive{.35f},levelDb{},bass{},lowMid{},highMid{},treble{},presence{},resonance{};bool mute{},solo{},polarity{},cab{true};float fineDelayMs{},cabLow{70.f},cabHigh{9000.f};};
class Crossover {
 using LR=juce::dsp::LinkwitzRileyFilter<float>; LR a,b,phase;
public:void prepare(const juce::dsp::ProcessSpec&s){a.prepare(s);b.prepare(s);phase.prepare(s);phase.setType(juce::dsp::LinkwitzRileyFilterType::allpass);set(150,1200);}
 void reset(){a.reset();b.reset();phase.reset();} void set(float x1,float x2){a.setCutoffFrequency(x1);b.setCutoffFrequency(x2);phase.setCutoffFrequency(x2);}
 void split(const juce::AudioBuffer<float>&in,std::array<juce::AudioBuffer<float>,3>&o){for(auto&x:o)x.setSize(in.getNumChannels(),in.getNumSamples(),false,false,true);for(int c=0;c<in.getNumChannels();++c)for(int n=0;n<in.getNumSamples();++n){float lo{},up{},mi{},hi{};a.processSample(c,in.getSample(c,n),lo,up);b.processSample(c,up,mi,hi);o[0].setSample(c,n,phase.processSample(c,lo));o[1].setSample(c,n,mi);o[2].setSample(c,n,hi);}}
};
class Amp {
 double sr{48000}; AmpModel model{AmpModel::glass}; float drive{.35f}; using IIR=juce::dsp::ProcessorDuplicator<juce::dsp::IIR::Filter<float>,juce::dsp::IIR::Coefficients<float>>; IIR lo,lm,hm,hi,pres,res; std::unique_ptr<juce::dsp::Oversampling<float>> os;
public:void prepare(const juce::dsp::ProcessSpec&s){sr=s.sampleRate;lo.prepare(s);lm.prepare(s);hm.prepare(s);hi.prepare(s);pres.prepare(s);res.prepare(s);os=std::make_unique<juce::dsp::Oversampling<float>>(s.numChannels,2,juce::dsp::Oversampling<float>::filterHalfBandPolyphaseIIR,true,true);os->initProcessing(s.maximumBlockSize);tone(0,0,0,0,0,0);}
 void reset(){lo.reset();lm.reset();hm.reset();hi.reset();pres.reset();res.reset();if(os)os->reset();} void set(AmpModel m,float d){model=m;drive=juce::jlimit(0.f,1.f,d);}
 float latency()const{return os?os->getLatencyInSamples():0.f;}
 void tone(float bass,float lowmid,float highmid,float treble,float presence,float resonance){float bf=80,lmf=450,hmf=1500,hf=4000,pf=2500,rf=90;if(model==AmpModel::ironTube){bf=40;lmf=220;hmf=800;hf=4000;rf=70;}else if(model==AmpModel::solidPunch){bf=60;lmf=250;hmf=1000;hf=5000;pf=4500;}else if(model==AmpModel::tight515){bf=110;lmf=500;hmf=1200;hf=3800;pf=2000;rf=95;}lo.state=juce::dsp::IIR::Coefficients<float>::makeLowShelf(sr,bf,.707f,juce::Decibels::decibelsToGain(bass));lm.state=juce::dsp::IIR::Coefficients<float>::makePeakFilter(sr,lmf,.8f,juce::Decibels::decibelsToGain(lowmid));hm.state=juce::dsp::IIR::Coefficients<float>::makePeakFilter(sr,hmf,.8f,juce::Decibels::decibelsToGain(highmid));hi.state=juce::dsp::IIR::Coefficients<float>::makeHighShelf(sr,hf,.707f,juce::Decibels::decibelsToGain(treble));pres.state=juce::dsp::IIR::Coefficients<float>::makeHighShelf(sr,pf,.8f,juce::Decibels::decibelsToGain(presence));res.state=juce::dsp::IIR::Coefficients<float>::makePeakFilter(sr,rf,1.1f,juce::Decibels::decibelsToGain(resonance));}
 void process(juce::AudioBuffer<float>&b){juce::dsp::AudioBlock<float>base(b);auto up=os->processSamplesUp(base);for(size_t c=0;c<up.getNumChannels();++c)for(size_t n=0;n<up.getNumSamples();++n){float x=up.getSample((int)c,(int)n),g=1.f+drive*18.f;switch(model){case AmpModel::glass:x=.9f*x+.1f*std::tanh(x*(1.f+drive));break;case AmpModel::ironTube:x=.58f*x+.42f*std::tanh((x+.08f*x*x)*(1.f+drive*7.f));break;case AmpModel::solidPunch:x=.25f*x+.75f*std::tanh(x*(1.f+drive*4.f));break;case AmpModel::modernBass:x=.5f*x+.5f*std::tanh(x*(1.f+drive*10.f));break;default:{float y=std::tanh(x*g);x=std::tanh((y-.03f*y*y)*(1.8f+drive*4.f));break;}}up.setSample((int)c,(int)n,x);}os->processSamplesDown(base);juce::dsp::ProcessContextReplacing<float>ctx(base);lo.process(ctx);lm.process(ctx);hm.process(ctx);hi.process(ctx);res.process(ctx);pres.process(ctx);}
};
class Cab{using IIR=juce::dsp::ProcessorDuplicator<juce::dsp::IIR::Filter<float>,juce::dsp::IIR::Coefficients<float>>;IIR hp,lp;juce::dsp::Convolution conv;double sr{48000};bool on{true};
public:void prepare(const juce::dsp::ProcessSpec&s){sr=s.sampleRate;hp.prepare(s);lp.prepare(s);conv.prepare(s);setCuts(70,9000);}void reset(){hp.reset();lp.reset();conv.reset();}void enable(bool x){on=x;}void setCuts(float a,float b){hp.state=juce::dsp::IIR::Coefficients<float>::makeHighPass(sr,a);lp.state=juce::dsp::IIR::Coefficients<float>::makeLowPass(sr,b);}bool load(const juce::File&f){if(!f.existsAsFile())return false;conv.loadImpulseResponse(f,juce::dsp::Convolution::Stereo::yes,juce::dsp::Convolution::Trim::yes,0,juce::dsp::Convolution::Normalise::yes);return true;}void process(juce::AudioBuffer<float>&b){if(!on)return;juce::dsp::AudioBlock<float>bl(b);juce::dsp::ProcessContextReplacing<float>ctx(bl);hp.process(ctx);conv.process(ctx);lp.process(ctx);}};
class Engine{std::array<Amp,3> amps;std::array<Cab,3> cabs;Crossover xo;std::array<juce::AudioBuffer<float>,3> work;
public:void prepare(const juce::dsp::ProcessSpec&s){xo.prepare(s);for(auto&a:amps)a.prepare(s);for(auto&c:cabs)c.prepare(s);}void reset(){xo.reset();for(auto&a:amps)a.reset();for(auto&c:cabs)c.reset();}
 void process(juce::AudioBuffer<float>&b,RoutingMode mode,float x1,float x2,const std::array<LaneState,3>&s){bool any=s[0].solo||s[1].solo||s[2].solo;if(mode==RoutingMode::matrix){xo.set(x1,x2);xo.split(b,work);}else{for(auto&w:work)w.makeCopyOf(b,true);}b.clear();int count=mode==RoutingMode::classic?1:mode==RoutingMode::dual?2:3;for(int i=0;i<count;++i){if(s[i].mute||(any&&!s[i].solo))continue;amps[i].set((AmpModel)juce::jlimit(0,7,s[i].amp),s[i].drive);amps[i].tone(s[i].bass,s[i].lowMid,s[i].highMid,s[i].treble,s[i].presence,s[i].resonance);amps[i].process(work[i]);cabs[i].enable(s[i].cab);cabs[i].setCuts(s[i].cabLow,s[i].cabHigh);cabs[i].process(work[i]);if(s[i].polarity)work[i].applyGain(-1.f);work[i].applyGain(juce::Decibels::decibelsToGain(s[i].levelDb));for(int c=0;c<b.getNumChannels();++c)b.addFrom(c,0,work[i],c,0,b.getNumSamples(),mode==RoutingMode::dual?.5f:1.f);}}
};
}
