#include "PluginEditor.h"
namespace {void rotary(juce::Slider&s){s.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s.setTextBoxStyle(juce::Slider::TextBoxBelow,false,58,18);}}
ChimeraAmpMatrixAudioProcessorEditor::ChimeraAmpMatrixAudioProcessorEditor(ChimeraAmpMatrixAudioProcessor&p):AudioProcessorEditor(&p){
 title.setText("SpectralForge | CHIMERA AMP MATRIX",juce::dontSendNotification);title.setJustificationType(juce::Justification::centred);title.setFont(juce::FontOptions(24.f).withStyle("Bold"));addAndMakeVisible(title);mode.addItemList({"Classic","Dual","Matrix"},1);addAndMakeVisible(mode);for(auto*s:{&x1,&x2}){rotary(*s);s->setTextValueSuffix(" Hz");addAndMakeVisible(*s);}
 auto&st=p.parameters();modeA=std::make_unique<ComboA>(st,"mode",mode);x1A=std::make_unique<SliderA>(st,"x1",x1);x2A=std::make_unique<SliderA>(st,"x2",x2);
 for(size_t i=0;i<lanes.size();++i){auto&l=lanes[i];const auto n=juce::String((int)i+1);l.name.setText("LANE "+n,juce::dontSendNotification);l.name.setJustificationType(juce::Justification::centred);addAndMakeVisible(l.name);l.amp.addItemList({"Glass","Tight 515","Iron Tube","Solid Punch"},1);addAndMakeVisible(l.amp);l.ampA=std::make_unique<ComboA>(st,"m"+n,l.amp);
  std::array<juce::Slider*,10> ss{&l.drive,&l.level,&l.bass,&l.mid,&l.treble,&l.presence,&l.resonance,&l.cabLow,&l.cabHigh,&l.delay};std::array<juce::String,10> ids{"ad"+n,"l"+n,"ab"+n,"am"+n,"at"+n,"ap"+n,"ar"+n,"cl"+n,"ch"+n,"d"+n};for(size_t k=0;k<ss.size();++k){rotary(*ss[k]);addAndMakeVisible(*ss[k]);l.sliders[k]=std::make_unique<SliderA>(st,ids[k],*ss[k]);}
  std::array<juce::ToggleButton*,4> bs{&l.mute,&l.solo,&l.polarity,&l.cab};std::array<juce::String,4> bids{"u"+n,"s"+n,"p"+n,"cab"+n};for(size_t k=0;k<bs.size();++k){addAndMakeVisible(*bs[k]);l.buttons[k]=std::make_unique<ButtonA>(st,bids[k],*bs[k]);}}
 setSize(1120,690);
}
void ChimeraAmpMatrixAudioProcessorEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff111318));g.setColour(juce::Colour(0xffd4d7dc));g.setFont(13.f);g.drawText("ROUTING",32,80,100,22,juce::Justification::centredLeft);g.drawText("X1",250,80,70,22,juce::Justification::centred);g.drawText("X2",340,80,70,22,juce::Justification::centred);for(int i=0;i<3;++i){auto x=25+i*365;g.setColour(juce::Colour(0xff242832));g.drawRoundedRectangle((float)x,210.f,345.f,445.f,10.f,1.5f);}}
void ChimeraAmpMatrixAudioProcessorEditor::resized(){title.setBounds(20,18,getWidth()-40,40);mode.setBounds(32,110,170,30);x1.setBounds(240,100,90,90);x2.setBounds(335,100,90,90);for(size_t i=0;i<lanes.size();++i){auto&l=lanes[i];int x=35+(int)i*365;l.name.setBounds(x,220,325,25);l.amp.setBounds(x+35,252,255,28);std::array<juce::Slider*,7> tone{&l.drive,&l.level,&l.bass,&l.mid,&l.treble,&l.presence,&l.resonance};for(size_t k=0;k<tone.size();++k)tone[k]->setBounds(x+(int)(k%4)*80,290+(int)(k/4)*100,72,86);l.cabLow.setBounds(x,500,90,90);l.cabHigh.setBounds(x+100,500,90,90);l.delay.setBounds(x+200,500,90,90);l.mute.setBounds(x,610,45,24);l.solo.setBounds(x+50,610,45,24);l.polarity.setBounds(x+100,610,50,24);l.cab.setBounds(x+165,610,70,24);}}
