#include "PluginProcessor.h"
#include "PluginEditor.h"
ChimeraAmpMatrixAudioProcessor::ChimeraAmpMatrixAudioProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),state(*this,nullptr,"STATE",createParameters()){}
void ChimeraAmpMatrixAudioProcessor::prepareToPlay(double sr,int bs){juce::dsp::ProcessSpec spec{sr,(juce::uint32)bs,(juce::uint32)getTotalNumOutputChannels()};preFx.prepare(spec);engine.prepare(spec);}
bool ChimeraAmpMatrixAudioProcessor::isBusesLayoutSupported(const BusesLayout&l)const{auto o=l.getMainOutputChannelSet();return(o==juce::AudioChannelSet::mono()||o==juce::AudioChannelSet::stereo())&&l.getMainInputChannelSet()==o;}
void ChimeraAmpMatrixAudioProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&){juce::ScopedNoDenormals n;auto f=[this](const char*i){return state.getRawParameterValue(i)->load();};auto q=[&](const char*i){return f(i)>.5f;};preFx.setGate(f("gateThreshold"),q("gateOn"));preFx.setBoost(f("boostGain"),q("boostOn"));preFx.setEq(f("eqLow"),f("eqMid"),f("eqHigh"),q("eqOn"));preFx.process(b);std::array<spectralforge::LaneSettings,3> ls{};for(int i=0;i<3;++i){auto n=juce::String(i+1);ls[(size_t)i].levelDb=f(("l"+n).toRawUTF8());ls[(size_t)i].model=(int)f(("m"+n).toRawUTF8());ls[(size_t)i].mute=q(("u"+n).toRawUTF8());ls[(size_t)i].solo=q(("s"+n).toRawUTF8());ls[(size_t)i].polarityInvert=q(("p"+n).toRawUTF8());ls[(size_t)i].fineDelayMs=f(("d"+n).toRawUTF8());}engine.process(b,(spectralforge::RoutingMode)(int)f("mode"),f("x1"),f("x2"),ls);}
juce::AudioProcessorEditor* ChimeraAmpMatrixAudioProcessor::createEditor(){return new ChimeraAmpMatrixAudioProcessorEditor(*this);}
juce::AudioProcessorValueTreeState::ParameterLayout ChimeraAmpMatrixAudioProcessor::createParameters(){std::vector<std::unique_ptr<juce::RangedAudioParameter>>p;p.push_back(std::make_unique<juce::AudioParameterBool>("gateOn","Gate",false));p.push_back(std::make_unique<juce::AudioParameterFloat>("gateThreshold","Gate Threshold",-80.f,-20.f,-55.f));p.push_back(std::make_unique<juce::AudioParameterBool>("boostOn","Boost",false));p.push_back(std::make_unique<juce::AudioParameterFloat>("boostGain","Boost Gain",0.f,18.f,6.f));p.push_back(std::make_unique<juce::AudioParameterBool>("eqOn","Pre EQ",false));p.push_back(std::make_unique<juce::AudioParameterFloat>("eqLow","Pre EQ Low",-12.f,12.f,0.f));p.push_back(std::make_unique<juce::AudioParameterFloat>("eqMid","Pre EQ Mid",-12.f,12.f,0.f));p.push_back(std::make_unique<juce::AudioParameterFloat>("eqHigh","Pre EQ High",-12.f,12.f,0.f));p.push_back(std::make_unique<juce::AudioParameterChoice>("mode","Routing",juce::StringArray{"Classic","Dual","Matrix"},0));p.push_back(std::make_unique<juce::AudioParameterFloat>("x1","Low Mid",juce::NormalisableRange<float>(60,800,1,.45f),150));p.push_back(std::make_unique<juce::AudioParameterFloat>("x2","Mid High",juce::NormalisableRange<float>(500,6000,1,.45f),1200));for(int i=1;i<=3;++i){auto n=juce::String(i);p.push_back(std::make_unique<juce::AudioParameterFloat>("l"+n,"Lane Level",-24,12,0));p.push_back(std::make_unique<juce::AudioParameterChoice>("m"+n,"Lane Amp",juce::StringArray{"Clean","Tight Drive","Bass Saturator"},i-1));p.push_back(std::make_unique<juce::AudioParameterBool>("u"+n,"Mute",false));p.push_back(std::make_unique<juce::AudioParameterBool>("s"+n,"Solo",false));p.push_back(std::make_unique<juce::AudioParameterBool>("p"+n,"Polarity",false));p.push_back(std::make_unique<juce::AudioParameterFloat>("d"+n,"Fine Delay",0.f,5.f,0.f));}return{p.begin(),p.end()};}
void ChimeraAmpMatrixAudioProcessor::getStateInformation(juce::MemoryBlock&d){if(auto x=state.copyState().createXml())copyXmlToBinary(*x,d);}
void ChimeraAmpMatrixAudioProcessor::setStateInformation(const void*d,int z){if(auto x=getXmlFromBinary(d,z))if(x->hasTagName(state.state.getType()))state.replaceState(juce::ValueTree::fromXml(*x));}
juce::AudioProcessor*JUCE_CALLTYPE createPluginFilter(){return new ChimeraAmpMatrixAudioProcessor();}
