// Generated by Tools/generate_post_native_catalog.py. Do not hand-edit.
#pragma once
#include <juce_core/juce_core.h>
#include <array>
#include <cmath>
namespace spectralforge {
inline constexpr int postNativeSectionCount=3, postNativeModelsPerSection=3, postNativeMaxControls=14;
enum class PostNativeControlKind { knob, choice, toggle };
struct PostNativeControl { const char* id; const char* label; PostNativeControlKind kind; float minimum, maximum, initial, interval; const char* options; bool connected; const char* note; };
struct PostNativeModel { const char* name; const char* reference; int controlCount; std::array<PostNativeControl,postNativeMaxControls> controls; };
inline const std::array<PostNativeModel,9> postNativeModels{{
    {"Console VCA","SSL XLogic G Series Compressor · 2005 Rev 0A",9, {{
        {"threshold","THRESHOLD",PostNativeControlKind::knob,-48.0f,0.0f,-18.0f,0.001f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"makeup","MAKE-UP",PostNativeControlKind::knob,0.0f,20.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"attack","ATTACK",PostNativeControlKind::choice,0.0f,5.0f,4.0f,1.0f,"0.1 ms|0.3 ms|1 ms|3 ms|10 ms|30 ms",true,""},
        {"release","RELEASE",PostNativeControlKind::choice,0.0f,4.0f,1.0f,1.0f,"0.1 s|0.3 s|0.6 s|1.2 s|AUTO",true,""},
        {"ratio","RATIO",PostNativeControlKind::choice,0.0f,2.0f,1.0f,1.0f,"2:1|4:1|10:1",true,""},
        {"compressor_in","COMPRESSOR IN",PostNativeControlKind::toggle,0.0f,1.0f,1.0f,1.0f,"",true,""},
        {"external_sidechain","EXTERNAL SIDE-CHAIN",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",false,"External sidechain bus is unavailable; internal stereo detector is used."},
        {"fade_rate","RATE",PostNativeControlKind::knob,1.0f,60.0f,10.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"auto_fade","AUTO FADE",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
    }}},
    {"FET Limiter","Universal Audio 1176LN · D/E-style hardware reissue",7, {{
        {"input","INPUT",PostNativeControlKind::knob,-24.0f,36.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"output","OUTPUT",PostNativeControlKind::knob,-36.0f,12.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"attack","ATTACK",PostNativeControlKind::knob,0.0f,1.0f,0.5f,0.001f,"",true,"Clockwise is faster; 0–1 is a position, not milliseconds. Digital implementation range; hardware taper uncalibrated."},
        {"release","RELEASE",PostNativeControlKind::knob,0.0f,1.0f,0.5f,0.001f,"",true,"Clockwise is faster; 0–1 is a position, not milliseconds. Digital implementation range; hardware taper uncalibrated."},
        {"attack_off","ATTACK OFF",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"ratio","RATIO",PostNativeControlKind::choice,0.0f,4.0f,0.0f,1.0f,"4:1|8:1|12:1|20:1|ALL BUTTONS",true,""},
        {"meter","METER",PostNativeControlKind::choice,0.0f,3.0f,0.0f,1.0f,"GR|+4|+8|OFF",true,"GR/output meter selection; OFF bypasses processing and blanks meter (software power proxy)."},
    }}},
    {"Optical Level","Teletronix LA-2A · Universal Audio hardware reissue",5, {{
        {"gain","GAIN",PostNativeControlKind::knob,-24.0f,24.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"peak_reduction","PEAK REDUCTION",PostNativeControlKind::knob,0.0f,100.0f,40.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"mode","MODE",PostNativeControlKind::choice,0.0f,1.0f,0.0f,1.0f,"COMPRESS|LIMIT",true,""},
        {"meter","METER",PostNativeControlKind::choice,0.0f,2.0f,1.0f,1.0f,"+4|GR|+10",true,""},
        {"r37","R37 · HF EMPHASIS",PostNativeControlKind::knob,0.0f,1.0f,1.0f,0.001f,"",true,"Clockwise is flat sidechain; not a front-panel attack control. Digital implementation range; hardware taper uncalibrated."},
    }}},
    {"Iron Colour","Neve 1073 Classic · preamplifier section",2, {{
        {"gain","MIC / LINE GAIN",PostNativeControlKind::choice,0.0f,20.0f,2.0f,1.0f,"LINE -10 dB|LINE -5 dB|LINE +0 dB|LINE +5 dB|LINE +10 dB|LINE +15 dB|LINE +20 dB|OFF|MIC +20 dB|MIC +25 dB|MIC +30 dB|MIC +35 dB|MIC +40 dB|MIC +45 dB|MIC +50 dB|MIC +55 dB|MIC +60 dB|MIC +65 dB|MIC +70 dB|MIC +75 dB|MIC +80 dB",true,""},
        {"phase","PHASE",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
    }}},
    {"Pure DI","Avalon V5 · mono DI / RE / mic preamp",7, {{
        {"input","INPUT",PostNativeControlKind::choice,0.0f,4.0f,0.0f,1.0f,"LINE|INST / DI|MIC HI-Z|MIC LO-Z|MIC +48 V",true,"Recorded-audio input voicing; MIC +48 V shares MIC response without phantom power."},
        {"boost","BOOST",PostNativeControlKind::choice,0.0f,20.0f,0.0f,1.0f,"1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21",true,""},
        {"tone","TONE",PostNativeControlKind::choice,0.0f,9.0f,0.0f,1.0f,"1|2|3|4|5|6|7|8|9|10",true,""},
        {"tone_in","TONE IN",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"high_cut","HIGH CUT",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"phase","PHASE",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"pad","PAD",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
    }}},
    {"Blue Channel","Focusrite ISA One · main and instrument preamps",12, {{
        {"input","INPUT",PostNativeControlKind::choice,0.0f,2.0f,1.0f,1.0f,"MIC|LINE|INST",true,""},
        {"gain","GAIN",PostNativeControlKind::choice,0.0f,3.0f,0.0f,1.0f,"0|10|20|30",true,""},
        {"gain_range","30–60",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"trim","TRIM",PostNativeControlKind::knob,0.0f,20.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"impedance","Z IN",PostNativeControlKind::choice,0.0f,3.0f,1.0f,1.0f,"LOW · 600 Ω|ISA 110 · 1.4 kΩ|MED · 2.4 kΩ|HIGH · 6.8 kΩ",false,"Physical microphone loading requires a source impedance model; unavailable for recorded audio."},
        {"phantom","+48 V",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",false,"Physical phantom power; unavailable in a software insert."},
        {"phase","PHASE",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"high_pass","HPF · 75 Hz",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"insert","INSERT",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",false,"External send/return is unavailable; internal signal path remains direct."},
        {"instrument_gain","GAIN",PostNativeControlKind::knob,10.0f,40.0f,10.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"instrument_z","Z IN",PostNativeControlKind::choice,0.0f,1.0f,0.0f,1.0f,"LOW|HIGH",false,"Physical instrument loading requires a pickup/source circuit; unavailable for recorded audio."},
        {"post_insert","POST INSERT",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,"Meter source switches between input and processed output; no external insert."},
    }}},
    {"Console Four","SSL E Series EQ · 500 Series / Brown-02 and Black-242",14, {{
        {"hf_gain","HF GAIN",PostNativeControlKind::knob,-18.0f,18.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"hf_frequency","HF FREQ",PostNativeControlKind::knob,1500.0f,22000.0f,8000.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"hf_bell","HF BELL",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"hmf_gain","HMF GAIN",PostNativeControlKind::knob,-18.0f,18.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"hmf_frequency","HMF FREQ",PostNativeControlKind::knob,600.0f,7000.0f,2000.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"hmf_q","HMF Q",PostNativeControlKind::knob,0.3f,6.0f,1.0f,0.001f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lmf_gain","LMF GAIN",PostNativeControlKind::knob,-18.0f,18.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lmf_frequency","LMF FREQ",PostNativeControlKind::knob,200.0f,2500.0f,600.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lmf_q","LMF Q",PostNativeControlKind::knob,0.3f,6.0f,1.0f,0.001f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lf_gain","LF GAIN",PostNativeControlKind::knob,-18.0f,18.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lf_frequency","LF FREQ",PostNativeControlKind::knob,30.0f,450.0f,80.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lf_bell","LF BELL",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"black","BLK",PostNativeControlKind::toggle,0.0f,1.0f,0.0f,1.0f,"",true,""},
        {"eq_in","IN",PostNativeControlKind::toggle,0.0f,1.0f,1.0f,1.0f,"",true,""},
    }}},
    {"Inductor EQ","Neve 1073 Classic · complete EQ section",7, {{
        {"hf_gain","HF GAIN · 12 kHz",PostNativeControlKind::knob,-16.0f,16.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"mf_gain","MF GAIN",PostNativeControlKind::knob,-18.0f,18.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"mf_frequency","MF FREQ",PostNativeControlKind::choice,0.0f,5.0f,0.0f,1.0f,"360 Hz|700 Hz|1.6 kHz|3.2 kHz|4.8 kHz|7.2 kHz",true,""},
        {"lf_gain","LF GAIN",PostNativeControlKind::knob,-16.0f,16.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lf_frequency","LF FREQ",PostNativeControlKind::choice,0.0f,3.0f,0.0f,1.0f,"35 Hz|60 Hz|110 Hz|220 Hz",true,""},
        {"high_pass","HIGH PASS",PostNativeControlKind::choice,0.0f,4.0f,0.0f,1.0f,"OFF|50 Hz|80 Hz|160 Hz|300 Hz",true,""},
        {"eq_in","EQL",PostNativeControlKind::toggle,0.0f,1.0f,1.0f,1.0f,"",true,""},
    }}},
    {"Passive Tube","Pulse Techniques Pultec EQP-1A · tube program EQ",9, {{
        {"lf_frequency","LOW FREQ",PostNativeControlKind::choice,0.0f,3.0f,0.0f,1.0f,"20 Hz|30 Hz|60 Hz|100 Hz",true,""},
        {"lf_boost","BOOST",PostNativeControlKind::knob,0.0f,13.5f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"lf_atten","ATTEN",PostNativeControlKind::knob,0.0f,17.5f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"bandwidth","BANDWIDTH",PostNativeControlKind::knob,0.0f,1.0f,0.5f,0.001f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"hf_boost","BOOST",PostNativeControlKind::knob,0.0f,18.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"hf_frequency","HIGH FREQ",PostNativeControlKind::choice,0.0f,6.0f,0.0f,1.0f,"3 kHz|4 kHz|5 kHz|8 kHz|10 kHz|12 kHz|16 kHz",true,""},
        {"hf_atten","ATTEN",PostNativeControlKind::knob,0.0f,16.0f,0.0f,0.01f,"",true,"Digital implementation range; hardware taper uncalibrated."},
        {"hf_atten_frequency","ATTEN SEL",PostNativeControlKind::choice,0.0f,2.0f,0.0f,1.0f,"5 kHz|10 kHz|20 kHz",true,""},
        {"eq_in","IN",PostNativeControlKind::toggle,0.0f,1.0f,1.0f,1.0f,"",true,""},
    }}},
}};
inline const PostNativeModel& postNativeModel(int section,int model) { return postNativeModels[static_cast<size_t>(juce::jlimit(0,2,section)*3+juce::jlimit(0,2,model))]; }
inline juce::String postNativePrefix(int section) { static const char* names[]{"bus","preamp","eq"}; return "pn_"+juce::String(names[juce::jlimit(0,2,section)]); }
inline juce::String postNativeModeID(int s) { return postNativePrefix(s)+"_native"; }
inline juce::String postNativeModelID(int s) { return postNativePrefix(s)+"_model"; }
inline juce::String postNativeBankPrefix(int s,int m) { return postNativePrefix(s)+"_m"+juce::String(m); }
inline juce::String postNativeBypassID(int s,int m) { return postNativeBankPrefix(s,m)+"_bypass"; }
inline juce::String postNativeTrimID(int s,int m) { return postNativeBankPrefix(s,m)+"_softwareTrim"; }
inline juce::String postNativeLevelID(int s,int m) { return postNativeBankPrefix(s,m)+"_softwareLevel"; }
inline juce::String postNativeControlID(int s,int m,int c) { return postNativeBankPrefix(s,m)+"_"+postNativeModel(s,m).controls[static_cast<size_t>(c)].id; }
struct PostNativeBank { bool bypass{true}; float trimDb{},levelDb{}; std::array<float,postNativeMaxControls> values{}; };
struct PostNativeSectionState { bool nativeEnabled{false}; int selected{}; std::array<PostNativeBank,3> banks{}; };
struct PostNativeState { std::array<PostNativeSectionState,3> sections{}; };
inline PostNativeState defaultPostNativeState(bool nativeEnabled=true) { PostNativeState state; for(int s=0;s<3;++s) { state.sections[s].nativeEnabled=nativeEnabled; for(int m=0;m<3;++m)for(int c=0;c<postNativeModel(s,m).controlCount;++c)state.sections[s].banks[m].values[c]=postNativeModel(s,m).controls[c].initial; } return state; }
inline void sanitisePostNativeState(PostNativeState& state) { for(int s=0;s<3;++s) { auto& section=state.sections[s]; section.selected=juce::jlimit(0,2,section.selected); for(int m=0;m<3;++m) { auto& bank=section.banks[m]; bank.trimDb=std::isfinite(bank.trimDb)?juce::jlimit(-24.f,24.f,bank.trimDb):0.f; bank.levelDb=std::isfinite(bank.levelDb)?juce::jlimit(-24.f,24.f,bank.levelDb):0.f; for(int c=0;c<postNativeModel(s,m).controlCount;++c) { const auto& spec=postNativeModel(s,m).controls[c]; float& value=bank.values[c]; value=std::isfinite(value)?juce::jlimit(spec.minimum,spec.maximum,value):spec.initial; if(spec.kind!=PostNativeControlKind::knob)value=std::round(value); if(!spec.connected)value=spec.initial; } } } }
} // namespace spectralforge
